Dataloaders (default prisma + lib)
MTES-MCT/trackdechets pull request #1116
Opened 2021-12-20 14:39 UTC by Riron

WIP

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
---

- [Ticket Favro]()

2022-01-11 15:04 UTC, elishowk requested changes
top merci

2022-01-11 15:04 UTC, elishowk commented on back/src/server.ts
> +import { createUserDataLoaders } from "./users/dataloders";
petite erreur typo dans le nom du fichier

2022-01-13 13:02 UTC, elishowk approved these changes

2022-01-25 14:54 UTC, benoitguigal approved these changes
Trop cool ! Je me pose juste la question de la pertinence (perf versus simplification) de l'introduction de la lib dataloader pour gérer des cas qui sont assez résiduels.

2022-01-26 07:54 UTC, Riron commented
Je n'ai pas l'impression que les dataloaders rajoutent trop de complexité. Au contraire d'ailleurs je trouve qu'utiliser la librairie explicitement est bien plus clair que le dataloading Prisma implicite.
A mon sens, dans une API Graphql ça a du sens d'avoir ce package à dispo. On aura probablement d'autres usages à l'avenir.

2022-01-26 07:54 UTC, merged