Flexibilisation de la signature du BSDD
MTES-MCT/trackdechets pull request #1186
Opened 2022-02-11 15:53 UTC by zhouzi

Cette PR a pour objectif de permettre de signer l'enlèvement initial et l'enlèvement après entreposage provisoire en deux temps. De cette façon le détenteur du déchet peut signer sur son appareil et le transporteur également.

Initialement on avait prévu de n'ajouter qu'une mutation `signedByProducer` et de continuer à utiliser `signedByTransporter` pour la signature transporteur. Je me suis vite rendu compte que ça ne serait pas possible, pour plusieurs raisons :

- Les informations transmises à la mutation `signedByTransporter` sont incomplètes et deviendraient ambigus : on peut renseigner `sentBy` qui correspond au nom de la personne qui a signé pour l'émetteur et `sentAt` qui correspond à la date de l'enlèvement. Dans cet esprit `signedByProducer` devrait remplir le champ `sentBy` et mettre la date dans un autre champ que `sentAt` donc peut-être une combinaison du type `sentBy` + `emittedAt`. Mais avoir un champ `sentBy` de remplit alors que le bordereau n'est pas `SENT` porte à confusion. De plus, il faudrait ajouter le nom du transporteur à la liste des paramètres requis (breaking change, en plus de créer une autre combinaison bizarre du type `takenOverBy` + `sentAt`).
- La mutation `signedByTransporter` est également utilisé pour signer l'enlèvement après entreposage provisoire. En plus de `signedByProducer` il aurait fallu `signedByTemporaryStorage`.

J'ai donc dû créer une mutation qui fonctionne avec le procédé de signature découpé et qui permet d'utiliser le code de signature. Et tant qu'à faire, je me suis calqué sur ce qu'on fait sur les nouvelles APIs.

À noter que je ne casse pas le fonctionnement des mutations actuelles. J'ajoute des champs mais je continue de remplir les champs historiques.

- [ ] Mettre à jour la mutation `signedByTransporter` pour remplir les nouveaux champs
- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente

---

- [Ticket ETQ Producteur je peux signer l'enlèvement](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-2326)
- [Ticket ETQ Eco-organisme je peux signer l'enlèvement](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-7251)
- [Ticket ETQ Transporteur je peux signer l'enlèvement](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-7254)

2022-02-22 13:36 UTC, zhouzi commented on back/src/forms/typeDefs/bsdd.objects.graphql
> +  signedAt: DateTime @deprecated(reason: "Voir takenOverAt / emittedAt")
Je crois que je me suis trompé là dessus, `signedBy` et `signedAt` ne sont pas les équivalents de `takenOverAt` / `emittedAt` mais plutôt `receivedAt`. À vérifier et corriger selon.

2022-02-22 15:46 UTC, zhouzi commented on back/src/forms/typeDefs/bsdd.objects.graphql
> +  signedAt: DateTime @deprecated(reason: "Voir takenOverAt / emittedAt")
Après vérification dans la mutation `signedByTransporter`, c'est bien ça : `signedAt` = `sentAt` et `signedBy` = `sentBy`. Il n'y a donc pas d'erreur.

2022-03-14 08:38 UTC, benoitguigal commented
Point à discuter suite retour utilisateur : https://trackdechets.zammad.com/#ticket/zoom/7279. Peut-on autoriser le producteur à supprimer un BSDD au statut `SIGNED_BY_PRODUCER`. J'aurais tendance à dire oui car il est le seul à avoir signé à ce stade.

2022-03-14 15:51 UTC, benoitguigal approved these changes
Super boulot, c'était pas évident à gérer

2022-03-14 15:51 UTC, benoitguigal commented on back/src/forms/elastic.ts
> +      setFieldTab("emitterCompanySiret", "isForActionFor");
Il faut changer les messages suivants du coup: 

![Capture d’écran 2022-03-14 à 16 26 45](https://user-images.githubusercontent.com/2269165/158205203-3717ce81-269c-4475-a7ac-147aecc4e387.png)

----

![Capture d’écran 2022-03-14 à 16 26 58](https://user-images.githubusercontent.com/2269165/158205101-cff9c70f-fc55-48dc-820a-c1d322def222.png)

2022-03-14 15:51 UTC, benoitguigal commented on back/src/forms/elastic.ts
> +      setFieldTab("emitterCompanySiret", "isForActionFor");
"En attente de signature par l'émetteur" plutôt ?


![Capture d’écran 2022-03-14 à 16 28 55](https://user-images.githubusercontent.com/2269165/158205582-9b5c7134-69fd-4063-ba50-1bad30a4dc99.png)

2022-03-14 15:51 UTC, benoitguigal commented on front/src/dashboard/components/BSDList/BSDD/WorkflowAction/SignEmissionForm.tsx
> +                je déclare prendre en charge le déchet.
Enlever "je déclare prendre en charge le déchet" qui est du ressort du transporteur.

2022-03-14 15:51 UTC, benoitguigal commented on front/src/dashboard/components/BSDList/BSDD/WorkflowAction/SignTransportForm.tsx
> +    <Modal onClose={onClose} ariaLabel="Signer pour le transporteur" isOpen>
C'est un peu déroutant de retrouver cette action dans l'onglet "Suivi" du producteur. On pourrait peut-être le laisser dans l'onglet "Pour Action" et ajouter un peu d'aide contextuelle sur la signature par le transporteur avec code de signature transporteur.

2022-03-14 15:51 UTC, benoitguigal commented on Changelog.md
> +    - `Form.sentAt` : remplacé par `Form.takenOverAt`, qui peut différer de `Form.emittedAt`.
est-ce que les champs `sentAt` et `sentBy` seront toujours remplis de façon temporaire ?

2022-03-14 15:51 UTC, benoitguigal commented on Changelog.md
> +  - Déprécation de la mutation `signedByTransporter`. Elle permet toujours de faire passer un bordereau du statut `SEALED` à `SENT` et de `RESEALED` à `RESENT` tout en remplissant les nouveaux champs
Peut-être préciser que cette mutation est remplacée par les deux mutations `signEmissionForm` et `signTransportForm` qui permet de faire en deux temps ce que `signedByTransporter` faisant en un coup ?

2022-03-16 09:04 UTC, zhouzi commented on front/src/dashboard/components/BSDList/BSDD/WorkflowAction/SignTransportForm.tsx
> +    <Modal onClose={onClose} ariaLabel="Signer pour le transporteur" isOpen>
Oui tu as raison. Et en même temps ça serait bizarre de l'avoir dans "Pour action" alors que l'émetteur n'est pas celui qu'on attends vraiment à ce moment là. Je ne suis pas sûr que ça soit un comportement qu'on souhaite encourager de toute façon. Il faut quand même souhaiter que le transporteur ait le moyen de présenter le bordereau.

Ça et le fait que c'est pas vraiment un besoin qu'on avait identifié (de permettre à l'émetteur de faire signer le transporteur), j'ai enlevé le bouton d'action complètement pour l'émetteur. On pourra toujours revenir dessus.

2022-03-17 07:52 UTC, benoitguigal commented
@zhouzi il faudrait s'assurer aussi que l'export du registre est bien mis à jour avec les deux nouvelles dates

2022-03-17 08:02 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/signTransportForm.ts
> +      sentAt: args.input.takenOverAt,
Il faudrait peut-être mettre à jour la référence de l'API pour `sentAt` qui précise "Date de l'envoi du déchet par l'émetteur (case 9)". On pourrait dire "Date de l'envoi du déchet par l'émetteur et de prise en charge du déchet par le transporteur"

2022-03-24 09:24 UTC, zhouzi commented on back/prisma/migrations/58_signature_flexibilization.sql
> +ADD COLUMN "emittedAt" TIMESTAMPTZ(6),
J'ai un doute sur le type à donner aux dates, je veux bien l'avis de @Riron à ce sujet.

2022-03-24 18:19 UTC, elishowk requested changes
Un test d'intégration est cassé, je sais pas si tu as vu ?
https://github.com/MTES-MCT/trackdechets/runs/5680528378?check_suite_focus=true

2022-03-25 11:06 UTC, Riron commented on back/prisma/migrations/58_signature_flexibilization.sql
> +ADD COLUMN "emittedAt" TIMESTAMPTZ(6),
C'est bien ça 👍

2022-03-25 14:08 UTC, elishowk requested changes
Il y a un test cassé tjs https://github.com/MTES-MCT/trackdechets/runs/5692410476?check_suite_focus=true

2022-03-25 15:14 UTC, zhouzi commented
> Un test d'intégration est cassé

@elishowk c'est un test qui échoue avec un timeout de temps en temps, ça y est c'est tout vert.

2022-03-27 19:47 UTC, providenz commented on front/src/dashboard/components/BSDList/BSDD/BSDDActions/BSDDActions.tsx
> +  if (form.status === FormStatus.SignedByProducer) {
Un ou deux commentaires pour expliquer les raisons métier de ces quelques lignes…

2022-03-27 20:20 UTC, providenz commented on front/src/dashboard/components/BSDList/BSDD/WorkflowAction/WorkflowAction.tsx
> +      if (
On se retrouve dans certains cas avec des boutons d'actions dans le tab "suivi", par ex avec un acteur à la fois transporteur et destinataire
<img width="952" alt="Capture d’écran 2022-03-27 à 22 16 22" src="https://user-images.githubusercontent.com/878396/160299305-e0ef877d-65a9-454b-9da9-d1f9ab9c503b.png">

2022-03-27 20:21 UTC, providenz approved these changes
Joli morceau, ça va bien faire ce que le titre de la PR annonce :)

2022-03-27 20:26 UTC, providenz commented
J'ai le front/package-lock qui semble pas à jour

2022-03-29 12:14 UTC, zhouzi commented on front/src/dashboard/components/BSDList/BSDD/WorkflowAction/WorkflowAction.tsx
> +      if (
Ouais, c'est un problème assez général qu'on a et qui est identifié dans plusieurs cartes. Par exemple si je suis producteur et transporteur, on a le bouton "Signer l'enlèvement" dans l'onglet "Suivi".

2022-03-29 12:15 UTC, zhouzi commented
> J'ai le front/package-lock qui semble pas à jour

J'ai refait un `npm install` de mon côté mais je ne vois pas de changement. On utilise peut-être une version différente de node / npm ?

2022-03-29 14:04 UTC, merged