Améliorations BSDA
MTES-MCT/trackdechets pull request #1271
Opened 2022-03-14 17:36 UTC by Riron

Multiples améliorations:
- quand on change de type de bordereau, nettoyage des entreprises qui ne sont pas censées apparaitre
- Enforce date de traitement > date de réception
- Modification de wording: "fin de chantier" de vient "Signature entreprise de travaux"
- Possibilité d'éditer customInfo & immats pour les transporteurs

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
---

- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-7555)
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-7554)
- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-7272)

2022-03-22 10:12 UTC, elishowk approved these changes
quelques warnings front, mais sinon LGTM

2022-03-24 18:17 UTC, elishowk requested changes
Il y a des tests d'inté sur le BDSA qui sont cassés

2022-03-25 13:59 UTC, elishowk approved these changes

2022-03-25 14:58 UTC, zhouzi approved these changes
J'ai l'impression que certains de ces changements mériteraient d'être ajoutés au change log.

2022-03-25 14:58 UTC, zhouzi commented on front/src/common/components/tags-input/TagsInput.tsx
> +  function onBlur(
Je crois comprendre que l'idée c'est d'ajouter la saisie de l'utilisateur comme un tag au moment du blur, l'équivalent d'appuyer sur la touche entrée.

Y'a moyen d'ajouter une fonction `addTag` avec ce code, de l'utiliser dans `onInputKeyDown` et `onBlur`. Ça réduirait le code dupliqué en le rendant plus facile à comprendre.

2022-03-25 17:38 UTC, merged