API : Ajout d'une entreprise intermédiaire sur BSDD
MTES-MCT/trackdechets pull request #1331
Opened 2022-04-13 15:07 UTC by elishowk

- Nombreux retours utilisateurs font état d'un établissement « intermédia﻿ire » qui joue un rôle sur le parcours du déchets, mais réglementairement n'a pas d'action sur la traçabilité.
- leur rôle: pouvoir réaliser un bordereau, le suivre, l'archiver et éventuellement disposer d'un registre (à voir). Ils n'ont pas d'action de signature règlementaire. 

- [ ] réutilisation de la table "Company" en base de données et d'une relation N à N entre "Form" et "Company" 
- [ ] ajout d'un champ Form.intermediaries : Company[] à l'API GraphQL 
- [ ] ajout d'un champ FormInput.intermediairies à l'API GraphQL. Ce champ se comporte comme un upsert. 
- [ ] Ajout des intermédiaires dans checkCanRead 
- [ ] L'intermédiaire peut créer et mettre à jour un bordereau via l'api
- [ ] Ajout des intermédiaires dans `isFollowFor` de l'index 
- [ ] Ajout au registre exhaustif
- [ ] Ajout des intermédiaires sur le PDF

# TODO

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
---

- [Ticket Favro]()

2022-04-19 13:14 UTC, benoitguigal commented
J'ai un petit doute sur le fait de lier la table `Form` à la table `Company`. Ça prend un peu le contrepied de ce qu'on l'on a fait pour les autres acteurs du BSDD (émetteur, transporteur(s), destination, négociant, courtier) pour lesquelles on a fait le choix de stocker les numéros SIRET directement dans `Form`.
Plusieurs problèmes que j'envisage : 
- Comment renseigner une entreprise intermédiaire qui n'est pas encore inscrite sur TD ? Rien n'indique dans la spec qu'il faut nécessairement être inscrit sur TD pour être visé en tant qu'intermédiaire. 
- Que se passe-t-il si un établissement est supprimé par son admin ?

2022-04-19 13:22 UTC, benoitguigal commented on back/src/forms/typeDefs/bsdd.inputs.graphql
> +  intermediaryCompanies: [ID!]
Il me semble que les `ID` des établissements ne sont pas exposés publiquement donc impossible d'ajouter en intermédiaire un établissement dont je ne suis pas membre.

2022-04-27 14:18 UTC, elishowk commented on back/src/forms/typeDefs/bsdd.inputs.graphql
> +  intermediaryCompanies: [ID!]
je change tout donc plus d'ID

2022-05-06 13:08 UTC, Riron commented on back/src/forms/types.ts
> +export type FormCompanyId = Pick<
Pourquoi `*CompanyId` ici ?
Enfin je comprend que ce sont des identifiants de company, mais des identifiants différents de l'`id` qu'on stocke. Je me demande donc si `companyId` ne porte pas un peu à confusion

2022-05-06 13:08 UTC, Riron commented on back/src/forms/types.ts
> +  intermediaries?: Intermediary[];
P-e pas besoin de l'objet `Intermediary` entier ici du coup non ? Juste siret & vatNumber ? Voir le seul des 2 champs qui est rempli

2022-05-06 13:08 UTC, Riron commented on back/src/forms/validation.ts
> +      "Le numéro de TVA français n'est pas valide, seul",
Il manque la fin de la phrase je crois, ou alors c'est pour donner un côté dramatique 😆

2022-05-11 09:18 UTC, elishowk commented on back/prisma/migrations/64_intermediary_form_association.sql
> +CREATE TABLE "default$default"."Intermediary" (
Yep, je mets `IntermediaryFormAssociation` ça irait ?

2022-05-11 09:23 UTC, elishowk commented on back/src/forms/types.ts
> +export type FormCompanyId = Pick<
oui, je renomme en `FormCompanies`

2022-05-11 09:23 UTC, elishowk commented on back/src/common/redis/users.ts
> +export const cacheCompanyIdKey = (userId: string): string =>
ok, je renomme aussi l'autre fonction équivalente pour les siret

2022-05-11 09:24 UTC, elishowk commented on back/src/forms/types.ts
> +  intermediaries?: Intermediary[];
Ici c'est la complexité des identifiants des entités légales... En effet il serait mieux d'explicitement mettre les 2 champs ciblés.

2022-05-17 15:40 UTC, elishowk commented on back/src/companies/resolvers/mutations/__tests__/verifyCompanyByAdmin.integration.ts
> +  afterEach(resetDatabase);
Je ne sais pas pourquoi ce test s'est mis à échouer, la Company était créé quand elle ne devait pas donc j'ai mis un reset après chaque `it`

2022-05-24 08:39 UTC, Riron approved these changes

2022-05-24 08:39 UTC, Riron commented on back/prisma/schema.prisma
> +  formId    String?
Est-ce qu'on ne devrait pas le rendre `NOT NULL` ? A priori c'est obligatoirement lié à un bordereau ?

2022-05-24 08:39 UTC, Riron commented on back/src/__tests__/factories.ts
> +  return siret.padStart(14, "1");
Juste pour info, pourquoi tu as du modifier ça ? Je vois que ca a demandé pas mal de modifs dans des tests bsff, bsvhu...

2022-05-24 08:39 UTC, Riron commented on back/src/forms/database.ts
> +  const transportSegments = await await prisma.form
```suggestion
  const transportSegments = await prisma.form
```

2022-05-24 08:39 UTC, Riron commented on back/src/forms/database.ts
> +    intermediaries: await prisma.intermediaryFormAssociation.findMany({
Pour profiter des dataloaders natifs Prisma, il vaudrait p-e mieux faire ici:
```suggestion
    intermediaries: await prisma.form
    .findUnique({
      where: { id: form.id }
    }).intermediarries()
```

2022-05-24 08:39 UTC, Riron commented on back/src/forms/permissions.ts
> +          intermediariesSiret: fullForm.intermediaries.map(
```suggestion
          intermediariesSirets: fullForm.intermediaries.map(
```

2022-05-24 08:39 UTC, Riron commented on back/src/forms/permissions.ts
> +          intermediariesVatNumber: fullForm.intermediaries.map(
Comme pour les transportSegments, vu que c'est des tableaux p-e mettre au pluriel
```suggestion
          intermediariesVatNumbers: fullForm.intermediaries.map(
```

2022-05-24 08:39 UTC, Riron commented on back/src/forms/permissions.ts
> +  const fullForm = await formToCompanies(form);
nitpick, mais ce n'est plus un `fullForm` du coup

2022-05-24 08:39 UTC, Riron commented on back/src/forms/resolvers/forms/intermediary.ts
> +    });
Encore une fois pour une histoire de dataloaders, je pense qu'il vaut mieux faire:
```suggestion
    const intermediaries = await prisma.form.findUnique({
      where: { id: form.id },
    }).intermediaries();
```

2022-05-24 08:56 UTC, elishowk commented on back/src/__tests__/factories.ts
> +  return siret.padStart(14, "1");
Oui c'est pour s'assurer de ne jamais rentrer dans le cas des company de test commençant par "000000". Parce que j'avais, dans d'autres PR, travaillé pas mal sur les Company de test avec des "00000" et je voulais être sûr qu'aucun test ne tombait dans ce cas particulier où pafois le code se comporte différemment, ex. `companyInfos`

2022-05-24 09:05 UTC, benoitguigal requested changes
Plusieurs remarques / questions : 
- Avec quel profil doivent s'inscrire les entreprises intermédiaires ? 
- Même si cette fonctionnalité ne concerne que l'API, il faudrait à minima que les entreprises intermédiaire puisse voir les bordereaux dans leur dashboard 
- si j'essaye d'update un BSDD en passant `null` explicitement à `intermediaries`, ça ne supprime pas les intermédiaires (à discuter)

2022-05-24 09:05 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/updateForm.ts
> +        deleteMany: {},
il sert à quoi le `deleteMany` là ?

2022-05-24 09:05 UTC, benoitguigal commented on back/src/forms/resolvers/queries/__tests__/formsRegister.integration.ts
> +        formsRegister(sirets: ["${company.siret}", "22222222222222"], exportType: OUTGOING, exportFormat: CSV) {
pourquoi as-tu été amené à changer les siret dans de nombreux tests ?

2022-05-24 09:05 UTC, benoitguigal commented on back/src/forms/typeDefs/bsdd.inputs.graphql
> +  mais pas à la responsabilité de la traçabilité. (entreprise de travaux, bureau d'étude, maitre d'oeuvre,
```suggestion
  mais pas à la responsabilité de la traçabilité (entreprise de travaux, bureau d'étude, maitre d'oeuvre,
```

2022-05-24 09:05 UTC, benoitguigal commented on front/src/common/fragments.ts
> +    intermediaries {
ce fragment n'est utilisé nul part pour l'instant il me semble

2022-05-24 09:26 UTC, elishowk commented on back/src/forms/validation.ts
> +  contact: yup.string().notRequired().nullable(),
OK on dit contact obligatoire

2022-05-24 09:55 UTC, elishowk commented on back/src/forms/validation.ts
> + * - only french companies are allowed
oui et je rajoute un test pour ça merci

2022-05-24 10:05 UTC, elishowk commented on back/src/forms/resolvers/mutations/updateForm.ts
> +      const intermediariesInput = intermediaries.map(companyInput => {
Je fixe ça

2022-05-24 10:10 UTC, elishowk commented
> * Avec quel profil doivent s'inscrire les entreprises intermédiaires ?

Pour le moment pas de contrainte là dessus.

> * Même si cette fonctionnalité ne concerne que l'API, il faudrait à minima que les entreprises intermédiaire puisse voir les bordereaux dans leur dashboard

C'est possible, sauf erreur, car les intermédiaires sont autorisés via `isFormContributor` dans `checkCanRead`

> * si j'essaye d'update un BSDD en passant `null` explicitement à `intermediaries`, ça ne supprime pas les intermédiaires (à discuter)

Alors je trouve ça plus sûr de passer explicitement [] pour vider le Form. Tu penses pas ?

2022-05-24 10:14 UTC, benoitguigal commented
> C'est possible, sauf erreur, car les intermédiaires sont autorisés via isFormContributor dans checkCanRead 

J'ai testé mais je ne le retrouve pas dans le dashboard, il faut modifier le comportement de l'indexation je pense

> Alors je trouve ça plus sûr de passer explicitement [] pour vider le Form. Tu penses pas ? 

Il faudrait voir le comportement qui est adopté par exemple pour les annexes 2. Ça se discute je trouve

2022-05-24 10:45 UTC, elishowk commented
> J'ai testé mais je ne le retrouve pas dans le dashboard, il faut modifier le comportement de l'indexation je pense

Ok je propose de garder ça pour la partie front à développer prochainement, qu'en penses-tu ?

2022-05-24 19:45 UTC, benoitguigal approved these changes

2022-05-25 09:36 UTC, elishowk commented on back/src/forms/resolvers/mutations/updateForm.ts
> +      const intermediariesInput = intermediaries.map(companyInput => {
Je rajoute un test d'inté

2022-05-25 09:37 UTC, merged