Hotfix mode de transport bsda
MTES-MCT/trackdechets pull request #1425
Opened 2022-05-30 09:36 UTC by providenz

Sur le bsda, la colonne mode de transport n'a pas de default. Si le bsda est créé via api sans spécifier le mode, la valeur reste à null, mais le select affiche "Route". Les utilisateurs se retrouvent bloqués (à moins d'agir sur le select).
Cette PR met un default sur le transport mode du bsda et remplit les données initiales des formulaires avec la valeur ROAD (pour les bsda déjà en db).

Par ailleurs, le champ worker.work.hasEmitterPaperSignature peut être null en db si le bsd est créé via en db, ce qui rend l'édition du bsd impossible car la valeur null est renvoyé par l'UI est le back attend un booleen. Ce champ est donc nettoyé dans le saveForm.

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [x] S'assurer que la numérotation des nouvelles migrations est bien cohérente
---

- [Ticket Favro]()

2022-05-30 12:21 UTC, Riron approved these changes

2022-05-31 07:58 UTC, elishowk requested changes

2022-05-31 07:58 UTC, elishowk commented on front/src/form/bsda/stepper/BsdaStepList.tsx
> +    // mean to edit it, and it is lcoked once signe by worker
```suggestion
    // mean to edit it, and it is locked once signed by worker
```

2022-05-31 14:09 UTC, elishowk approved these changes

2022-05-31 15:19 UTC, merged