BSDD: transporteur & destination doivent être inscrits
MTES-MCT/trackdechets pull request #1451
Opened 2022-06-08 14:48 UTC by Riron

On empêche la création de bordereaux pour certains acteurs si ils ne sont pas inscrits:
- transporteur
- destination
- temp storage destination
- temp storage transporter

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
---

- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-7281)

2022-06-08 16:18 UTC, Riron commented on back/src/__tests__/factories.ts
> +  return siret.padStart(14, "9");
Avec le 1, on avait une erreur dès qu'on avait 11 créations de companies (`111 === 111` !). La on est bon jusqu'à 99, ce qui devrait suffire.
L'idéal est de pad avec des `0` mais tu disais que ca pose problème quelque part @elishowk je crois ?

2022-06-10 13:18 UTC, elishowk commented on back/src/__tests__/factories.ts
> +  return siret.padStart(14, "9");
Oui, faut éviter les "00000" pour éviter à tout pris de tomber dans le cas des SIRET de "test company" dans le code

2022-06-10 13:20 UTC, elishowk submitted a review, later dismissed

2022-06-15 09:11 UTC, benoitguigal requested changes
Pour l'entreposage provisoire, il faut également faire la vérification dans `markAsResealed` sinon on peut mettre n'importe quoi. Par ailleurs, contrairement à ce qui est dit dans la description de la PR 

> La vérification sur la destination n'était en fait réalisée qu'en front ! 

La vérification pour la destination est bien faite côté back mais au moment de `markAsSealed` et `markAsResealed`. 
Cf : 
- https://github.com/MTES-MCT/trackdechets/blob/bf330ed15f04d1d4ffaba42a8916259b88f26146/back/src/forms/resolvers/mutations/markAsSealed.ts#L28 
- https://github.com/MTES-MCT/trackdechets/blob/bf330ed15f04d1d4ffaba42a8916259b88f26146/back/src/forms/resolvers/mutations/markAsResealed.ts#L48

Cette vérification porte également sur le type de profil et le fait que l'entreprise soit vérifié. Il faudrait donc mettre tout ça au même endroit : 
- soit on intègre la vérification transporteur au code existant dans `checkCompaniesType`(en vérifiant au passage le statut de transporteur tant qu'à faire)
- soit on déplace le code vérification existant dans `createForm` et `updateForm`

2022-07-14 12:45 UTC, elishowk commented
Pourquoi pas généraliser à tous les schema de validation backend de tous les bordereaux pour les destinations et transporteurs, un truc comme ça par exemple pour le BSDA `destinationSchema` (pour Form il y a `isDraft`à passer dans le test
```
      destinationCompanySiret: yup
        .string()
        .length(14, `Entreprise de destination: ${INVALID_SIRET_LENGTH}`)
        .requiredIf(
          context.emissionSignature,
          `Entreprise de destination: ${MISSING_COMPANY_SIRET}`
        )
        .test(
          "is-registered-test",
          `Cet établissement n'est pas inscrit sur Trackdéchets.`,
          async value => {
            if (context.emissionSignature && value) {
              const isRegistered =
                (await prisma.company.count({
                  where: {
                    siret: value
                  }
                })) > 0;
              // it should be registered to TD
              if (isRegistered === false) {
                return false;
              }
            }
            return true;
          }
        ),
```

2022-07-25 16:41 UTC, Riron commented
> Pourquoi pas généraliser à tous les schema de validation backend de tous les bordereaux pour les destinations et transporteurs, un truc comme ça par exemple pour le BSDA `destinationSchema` (pour Form il y a `isDraft`à passer dans le test

Bonne idée, je switch sur quelque chose du genre 👍

2022-07-25 16:42 UTC, Riron commented
> > La vérification sur la destination n'était en fait réalisée qu'en front !
> 
> La vérification pour la destination est bien faite côté back mais au moment de `markAsSealed` et `markAsResealed`. Cf :

Bien vu, j'avais loupé ça, ne voyant pas d'erreur en créant mon bordereau.
Pour être cohérent avec le message front mieux vaut que le message s'affiche immédiatement, pas besoin d'attendre la signature.

2022-08-23 08:03 UTC, merged