Fix La référence API Dasri contient le schéma de `Form`
MTES-MCT/trackdechets pull request #1457
Opened 2022-06-13 08:12 UTC by benoitguigal

2022-06-13 08:28 UTC, elishowk commented
Le build de la doc ne marche plus du coup
> Error:  Error: Unknown type "SignatureAuthor". Did you mean "SignatureWhere" or "Signature"?

2022-06-13 08:28 UTC, elishowk requested changes
La doc ne build plus : `Error:  Error: Unknown type "SignatureAuthor". Did you mean "SignatureWhere" or "Signature"?`

2022-06-13 15:43 UTC, providenz commented
Yep, c'est pour ça que j'avais ajouté forms, j'avais pas percuté que ça dupliquait tout dans la doc dasri, faut passer SignatureAuthor dans common.enums.graphql

2022-06-14 12:58 UTC, benoitguigal commented
> Yep, c'est pour ça que j'avais ajouté forms, j'avais pas percuté que ça dupliquait tout dans la doc dasri, faut passer SignatureAuthor dans common.enums.graphql

Merci c'est corrigé

2022-06-15 07:46 UTC, providenz approved these changes

2022-06-15 07:58 UTC, elishowk approved these changes

2022-06-15 13:59 UTC, merged