Removes '---' from foreign companies name / address
MTES-MCT/trackdechets pull request #1486
Opened 2022-06-27 14:52 UTC by kornifex

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
---

- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-8364)

2022-06-29 11:49 UTC, elishowk requested changes
il manque je crois côté front, le fait de rendre éditable les champs du formulaire au retour de la requête, parce qu'ils seront bloqués avec des champs vides

2022-06-30 07:56 UTC, kornifex commented
Si aucune info n'est renseignée alors le front propose un formulaire.
A moins que tu ne penses à autre chose ?

![image](https://user-images.githubusercontent.com/453215/176624115-f297a502-63de-4fb4-8beb-8536ede09510.png)

2022-06-30 12:01 UTC, benoitguigal commented
Je ne sais pas si c'est lié à cette PR mais en base de données, toutes les adresses des transporteurs UE qui ne sont pas "---" apparaissent tronquées.

2022-06-30 12:47 UTC, kornifex commented
Je reproduis pas en local. Tu as des exemples d'adresses tronquées ? Tu vois ça dans l'aperçu ? Dans le formulaire ?

2022-07-01 08:30 UTC, benoitguigal commented
> Je reproduis pas en local. Tu as des exemples d'adresses tronquées ? Tu vois ça dans l'aperçu ? Dans le formulaire ?

Dans les données de la base de prod sur les entreprises inscrites avec un numéro de TVA étranger

2022-07-01 13:01 UTC, Riron approved these changes

2022-07-01 16:06 UTC, merged