Fix/Transaction & workflow BSDD
MTES-MCT/trackdechets pull request #1502
Opened 2022-06-30 12:57 UTC by Riron

WIP

2022-06-30 15:47 UTC, elishowk approved these changes

2022-06-30 16:27 UTC, benoitguigal requested changes
Super ! 
Pour aller jusqu'au bout, il manque juste à mon avis le fait d'inclure les `update`, `delete` d'annexes 2 dans la transaction.

2022-06-30 16:27 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/markAsProcessed.ts
>    // mark appendix2Forms as PROCESSED
Ici il faudrait inclure la mise à jour des annexes 2 dans la même transaction

2022-06-30 16:27 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/markAsSealed.ts
>    if (appendix2Forms.length > 0) {
Ici il faudrait que la mise à jour des annexes 2 soit inclut dans la transaction

2022-06-30 16:27 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/markAsAccepted.ts
>      await formRepository.removeAppendix2(id);
il faudrait inclure cette ligne dans la transaction

2022-06-30 16:27 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/markAsReceived.ts
>    // check for stale transport segments and delete them
inclure la suite des écritures dans une seule transaction

2022-06-30 16:27 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/markAsTempStored.ts
>    // check for stale transport segments and delete them
inclure la suite du code dans la transaction

2022-06-30 16:27 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/markAsTempStorerAccepted.ts
>      if (
inclure la suite du code dans la transaction

2022-06-30 16:27 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/markAsSent.ts
>    if (appendix2Forms.length > 0) {
inclure la suite du code dans la transaction

2022-07-01 09:49 UTC, Riron commented
> Pour aller jusqu'au bout, il manque juste à mon avis le fait d'inclure les `update`, `delete` d'annexes 2 dans la transaction.

Carrément ! c'est fait

2022-07-01 14:58 UTC, benoitguigal approved these changes
Quelques lectures en DB qui peuvent éventuellement se faire hors de la transaction.

2022-07-01 14:58 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/markAsProcessed.ts
> +    const { findAppendix2FormsById, updateAppendix2Forms, update } =
il me semble que tu peux appeler `findAppendix2FormsById` en dehors de la transaction

2022-07-01 14:58 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/markAsSealed.ts
> +      return expandFormFromDb(updatedForm);
Tu as deux `expandFormFromDb` à la suite ici il me semble

2022-07-01 14:58 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/markAsSealed.ts
> +      const emitterCompanyExists =
peut également être calculé en dehors de la transaction

2022-07-01 14:58 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/markAsSent.ts
> +    const appendix2Forms = await findAppendix2FormsById(form.id);
peut-être calculé en dehors de la transaction

2022-07-01 15:00 UTC, benoitguigal commented on back/src/forms/resolvers/mutations/markAsSealed.ts
> +      const emitterCompanyExists =
D'ailleurs dans le cas des navires étrangers et OMI on appelle deux fois l'`update`, ça doit surement pouvoir s'optimiser

2022-07-04 07:09 UTC, merged