Adds noindex to sandbox / recette
MTES-MCT/trackdechets pull request #1507
Opened 2022-07-04 10:48 UTC by kornifex

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
---

- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-8420)

2022-07-05 16:21 UTC, elishowk commented on front/server.js
> +  if (process.env.BUILD_ENV !== "production") {
Pourquoi cette var et pas NODE_ENV ? (juste pour ma gouverne 🙏🏾 )

2022-07-05 16:21 UTC, elishowk approved these changes

2022-07-06 07:33 UTC, benoitguigal requested changes

2022-07-06 07:33 UTC, benoitguigal commented on front/server.js
> +    const raw = fs.readFileSync(pathToIndex, "utf8");
Est-ce qu'on ne pourrait pas charger la page (et faire la substitution noindex) en mémoire en dehors des routes au chargement de l'appli ? Ça éviterait au passage le warning CodeQL.

2022-07-07 11:51 UTC, merged