Update AccountCompanyAddSiret.tsx
MTES-MCT/trackdechets pull request #1511
Opened 2022-07-05 17:01 UTC by chrischarousset

changement email de contact + ajout lien pour Attestation INSEE

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
---

- [Ticket Favro]()

2022-07-06 07:11 UTC, benoitguigal requested changes

2022-07-06 14:27 UTC, benoitguigal approved these changes

2022-07-06 14:27 UTC, benoitguigal commented on front/src/account/accountCompanyAdd/AccountCompanyAddSiret.tsx
> +                "Vous devez entrer un numéro de TVA intracommunautaire valide. Veuillez nous contacter à l'adresse contact@trackdechets.beta.gouv.fr avec un justifictif légal du pays d'origine.",
```suggestion
                "Vous devez entrer un numéro de TVA intracommunautaire valide. Veuillez nous contacter à l'adresse contact@trackdechets.beta.gouv.fr avec un justificatif légal du pays d'origine.",
```

2022-07-07 11:49 UTC, kornifex approved these changes

2022-07-07 12:05 UTC, merged

2022-07-07 12:21 UTC, Riron approved these changes