Recette DASRI
MTES-MCT/trackdechets pull request #1540
Opened 2022-07-13 15:34 UTC by benoitguigal

- Correction du nombre de décimal sur les volumes totaux. 

![precision](https://user-images.githubusercontent.com/2269165/178772631-0fae082a-eb59-4948-9615-483c022a616a.png)

- Suppression d'un hook de calcul automatique des packagings transporteur et destinataire lors d'une modification d'un BSDASRI ce qui amenait à avoir des valeurs de packagings différents entre émetteur, transporteur et destinataire. [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/02f1ec52bd91efc0adb3c38b?card=tra-8687)

- Ajout d'une validation sur le nombre de colis

![image](https://user-images.githubusercontent.com/2269165/178773321-828f0d20-8695-4299-a61d-034d1e4401de.png)

- Ajout d'un retour à la ligne entre chaque contenant dans le composant `BsdasriWasteSummary`

![Capture d’écran 2022-07-13 à 17 44 37](https://user-images.githubusercontent.com/2269165/178776002-a4fa1ace-dc5c-411c-9ae1-58a32f03a753.png)

---

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
---

- [Ticket Favro]()

2022-07-14 09:06 UTC, elishowk requested changes
Les tests sont cassés

2022-07-15 07:55 UTC, benoitguigal commented
> Les tests sont cassés

Ok c'est good, je crois que c'était juste les tests qui étaient cassés sur `dev`. Ça a été corrigé depuis.

2022-07-15 08:00 UTC, providenz approved these changes

2022-07-15 08:48 UTC, elishowk approved these changes

2022-07-15 08:52 UTC, merged