Fix  Révision BSDA & changement de code d'opération
MTES-MCT/trackdechets pull request #1693
Opened 2022-09-15 12:32 UTC by Riron

Se référer au ticket pour le descriptif du bug: https://favro.com/organization/ab14a4f0460a99a9d64d4945/b64d96be58e6a57fe4d5c049?card=tra-8907

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
---

- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/b64d96be58e6a57fe4d5c049?card=tra-8907)

2022-09-15 12:54 UTC, elishowk approved these changes

2022-09-15 12:55 UTC, elishowk requested changes
Un test d'inté qui ne passe pas :
![image](https://user-images.githubusercontent.com/76620/190409130-533727fe-6f5e-40fd-b4dd-4af89ca606e1.png)

2022-09-16 10:37 UTC, Riron commented
Hyper bizarre que ca se soit mis à planter maintenant. Ca a à priori rien à voir avec ma PR.

2022-09-19 07:23 UTC, benoitguigal approved these changes

2022-09-19 08:25 UTC, providenz approved these changes

2022-09-19 08:28 UTC, merged