Removes limitation for emitter on a BSDD with eco-organisme
MTES-MCT/trackdechets pull request #1808
Opened 2022-10-26 15:26 UTC by kornifex

- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/02f1ec52bd91efc0adb3c38b?card=tra-8668)

2022-10-27 12:41 UTC, elishowk commented
Est-ce que ça fait partie de la recette en cours ? Parce que c'est un changement "délicat" à faire en cours de recette

2022-11-10 15:36 UTC, benoitguigal approved these changes

2022-11-11 09:55 UTC, elishowk commented on back/src/forms/resolvers/mutations/__tests__/markAsSealed.integration.ts
> -  it("should fail if bsd has an eco-organisme and the wrong emitterType", async () => {
Ne doit-on pas mieux remplacer ce test par des tests pour vérifier qu'on peut avoir tous les types d'eco-org ?

2022-11-11 10:03 UTC, elishowk commented on front/src/form/bsdd/components/eco-organismes/EcoOrganismes.tsx
> -            Indiquez dans la partie <strong>"Entreprise émettrice"</strong>{" "}
nit. : ne faut-il pas vérifier dans la documentation api aussi qu'il n'y ai plus de référence à cette limitation ?

2022-11-11 10:03 UTC, elishowk requested changes
2 petites questions

2022-11-15 09:26 UTC, elishowk approved these changes

2022-11-15 09:31 UTC, Riron approved these changes

2022-11-15 16:20 UTC, merged