Update password policy
MTES-MCT/trackdechets pull request #1857
Opened 2022-11-14 14:17 UTC by providenz

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
- [ ] Informer le data engineer de tout changement de schéma DB
---

- [Ticket Favro]()

2022-11-15 08:58 UTC, benoitguigal requested changes
Est-ce que ce n'est pas plutôt quelque chose à implémenter côté front vu qu'il n'est de toute façon pas possible d'effectuer ces actions par API. Il y a des exemples de regex que l'on peut utiliser directement.

2022-11-15 09:11 UTC, benoitguigal requested changes
Est-ce que ce n'est pas plutôt quelque chose à implémenter côté front vu qu'il n'est de toute façon pas possible d'effectuer ces actions par API. Il y a des exemples de regex que l'on peut utiliser directement.

2022-11-15 09:12 UTC, benoitguigal requested changes
Est-ce que ce n'est pas plutôt quelque chose à implémenter côté front vu qu'il n'est de toute façon pas possible d'effectuer ces actions par API. Il y a des exemples de regex que l'on peut utiliser directement.

2022-11-15 19:05 UTC, providenz commented
@benoitguigal Je n'ai pas encore sollicité de review :) mais non, implémenter une politique de sécu uniquement côté front, ça serait une très mauvaise pratique. Par exemple ça n'adresse absolument pas l'attaque par mot de passe très longs, et le "pas possible par l'api" n'est pas très difficile à contourner ;)

2022-12-01 10:33 UTC, Riron approved these changes
Top !
Je ne comprend juste pas trop à quoi sert le `passwordVersion`.
> stocke un numéro de version associé au mdp pour un éventuel renouvellement forcé à venir

Tu veux dire si on veut obliger l'utilisateur à changer de mot de passe ? Dans ce cas, est-ce qu'il ne "suffit" pas d'overrider son mot de passe par une string genre `FORCE_RENEW` par ex ?

2022-12-01 13:26 UTC, providenz commented
C'est pour savoir si un mdp donné matche les specs actuelle. Si on veut forcer les gens à mak leur mdp, inutile d'inclure ceux dont les mdp sont déjà "aux normes"
Je vais préciser.

> Top ! Je ne comprend juste pas trop à quoi sert le `passwordVersion`.

2022-12-01 13:47 UTC, Riron commented
Je vois.
Juste qques remarques:
- si on veut forcer à maj, pourquoi ne pas le faire tout de suite et ne pas s'embêter à rajouter un champ ?
- pour tous les mdps existants, il y en a probablement un grosse partie déjà aux normes. On ne peut pas faire la diff sur les mdps déjà existants
- forcer un changement de mdp est toujours relou pour les utilisateurs. A voir si on souhaite le faire ou pas

Je comprend bien que le champ en db permet de reporter ces décisions à plus tard. Je ne sais pas si on pourrait décider ça maintenant ?

2022-12-01 13:50 UTC, providenz commented
Ouais j'ai hésité, mais comme on n'a pas pris le temps d'en discuter j'ai ajouté ce champ qu'on pourra virer ou exploiter au besoin.

2022-12-02 08:40 UTC, elishowk commented on back/src/companies/resolvers/mutations/renewSecurityCodeService.ts
> +export async function renewSecurityCodeFn(
Est-ce que quelque chose à changé dans le code de cette fonction avant son déplacement ?

2022-12-02 08:42 UTC, elishowk commented on back/src/companies/resolvers/mutations/updateCompany.ts
> -export async function updateCompanyFn({
ce déplacement est hors-scope non ?

2022-12-02 08:47 UTC, elishowk approved these changes
quelques remarques mais LGTM

2022-12-02 08:47 UTC, elishowk commented on back/src/users/resolvers/mutations/inviteUserToCompanyService.ts
> +export async function inviteUserToCompanyFn(
nit. L'introduction de ces fichiers "service" à côté des mutations, pourquoi pas, je trouve que ça gonfle le nombre de fichiers dans le dossier des mutations, rendant moins clair la liste des mutations disponibles IMO

2022-12-02 20:29 UTC, providenz commented on back/src/companies/resolvers/mutations/updateCompany.ts
> -export async function updateCompanyFn({
Nope

2022-12-02 20:30 UTC, providenz commented on back/src/companies/resolvers/mutations/renewSecurityCodeService.ts
> +export async function renewSecurityCodeFn(
Nope

2022-12-02 20:31 UTC, providenz commented on back/src/users/resolvers/mutations/inviteUserToCompanyService.ts
> +export async function inviteUserToCompanyFn(
C'est simplement pour que les tests (*.test) passent sans avoir à mocker trouzemille dépendances.

2022-12-03 09:01 UTC, merged