Remove nextDestinationCompanyCountry
MTES-MCT/trackdechets pull request #1917
Opened 2022-11-25 15:44 UTC by Riron

PR qui fait suite à un ticket de Mr Duret: https://trackdechets.zammad.com/#ticket/zoom/18484

Par cohérence avec les autres inputs entreprises, il faut selon moi retirer le country de `nextDestination`.
J'en profite pour améliorer un peu le retour de l'api sur le champ country quand on a un vatNumber. Actuellement il semble que ca renvoyait systématiquement "FR".

PR à bien checker 😅

2022-11-28 08:57 UTC, elishowk requested changes

2022-11-28 08:57 UTC, elishowk commented on back/src/forms/resolvers/FormCompany.ts
> +      const { country } = checkVAT(parent.vatNumber, countries);
Attention checkVAT ne renvoie pas nécessairement le bon pays dans le cas de MONACO, dont les TVA commencent par FR, cf. la PR sur laquelle je travaille en ce moment https://github.com/MTES-MCT/trackdechets/pull/1905/files#diff-225db50e03b40ec6d1541bfd3c4488d044ba23b39ce1f30c30beb9

2022-11-28 09:11 UTC, elishowk commented on back/src/forms/resolvers/FormCompany.ts
> +      return country?.isoCode?.short;
Les points d'attention IMO : 
- `front/src/common/validation/schema.ts` le schema companySchema front qui necessite country
- `CompanySelector` s'initialise avec `country` https://github.com/MTES-MCT/trackdechets/blob/c32ce97485a17b1fd0658ad1aa96cd2219316191/front/src/form/common/components/company/CompanySelector.tsx#L77

2022-11-28 09:22 UTC, Riron commented on back/src/forms/resolvers/FormCompany.ts
> +      const { country } = checkVAT(parent.vatNumber, countries);
Tu sais si on a un moyen de différencier Monaco / france ?
Auparavant on retournait systématiquement "FR" semble t il, quel que soit le numéro.

2022-11-28 15:44 UTC, Riron commented on back/src/forms/resolvers/FormCompany.ts
> +      const { country } = checkVAT(parent.vatNumber, countries);
D'ailleurs dans les favoris on retourne FR aussi pour ce genre de vatNumber. Pas certain qu'on puisse faire beaucoup mieux.

2022-11-29 08:04 UTC, Riron commented on back/src/forms/resolvers/FormCompany.ts
> +      const { country } = checkVAT(parent.vatNumber, countries);
Bon j'ai vu ta PR sur Monaco et que tu essayais de le déduire de l'adresse. On pourra peut être améliorer ce bout de code une fois que ta PR sera mergée

2022-11-29 09:56 UTC, elishowk commented on back/src/forms/resolvers/FormCompany.ts
> +      return country?.isoCode?.short;
En clair, ce que veut dire mon dernier commentaire c'est: comment vérifier le bon fonctionnement de `CompanySelector` et  de la validation `companySchema` après ce changement dans `nextDestination` ? Je sais qu'il nous manque de la couverture de tests front, cependant je me méfie d'autant plus qu'un retrait de `nextDestination.country` risque bien de casser ces comportements front cités ci dessus

2022-12-01 09:07 UTC, benoitguigal commented
Est-ce qu'on peut commencer par spécifier dans une carte Favro le comportement voulu ?
Comme précisé dans ticket Zammad, le n°VAT est une donnée rarement disponible. À la lecture de l'arrêté, il n'est pas évident que l'obligation de saisir un n°TVA s'applique à la destination ultérieure. 

<img width="1162" alt="Capture d’écran 2022-12-01 à 10 00 33" src="https://user-images.githubusercontent.com/2269165/205010368-b0836d8d-d169-4a45-b295-c66daa88ddee.png">

Cette modification n'aurait peut-être pas eu lieu d'être : https://favro.com/organization/ab14a4f0460a99a9d64d4945/b64d96be58e6a57fe4d5c049?card=tra-10074

À mon avis le bon comportement serait donc : 
- En cas d'entreprise étrangère, on peut renseigner soit le `vatNumber` soit le `country`
- Si le `vatNumber` et `country` sont renseignés en même temps, péter une erreur si le numéro pays extrait du `vatNumber` ne correspond pas à la valeur de `country`.
- Péter une erreur si ni `siret`, ni `vatNumber`, ni `country` ne sont spécifiés

2022-12-02 08:32 UTC, Riron commented
Je pensais qu'on avait soit un siret soit un vatNumber. Visiblement, ce n'est pas le cas. Et si c'est envoyé hors europe on ne pourra pas déduire le pays.
Donc en effet il faut revoir la carte que tu as citée, et garder un champ country ici.

Je vais fermer cette PR et je reprendrai plus tard.
Ca se voulait être un correctif rapide. Ca demande en fait des discussions pour qu'on soit certain de partir sur ce qu'il faut.

2022-12-02 08:32 UTC, closed without merging