docs: fixing onboarding documentation omissions & adding a 'troubleshooting' section
MTES-MCT/trackdechets pull request #1929
Opened 2022-11-30 13:05 UTC by GaelFerrand

# Summary

In CONTRIBUTIN.md
- Fixing the docker-compose line to include the mongodb container
- Adding a troubleshooting section with:
  - How to solve the default$default issue
  - How to solve the elastic search export issue

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
- [ ] Informer le data engineer de tout changement de schéma DB
---

(pas de ticket favro)

2022-11-30 13:10 UTC, GaelFerrand commented on CONTRIBUTING.md
>      - [Créer un tampon de signature pour la génération PDF](#créer-un-tampon-de-signature-pour-la-génération-pdf)
The more human-readeabl, interpreted version [here](https://github.com/MTES-MCT/trackdechets/blob/f0d4e2876ccd564c1bab7b04501c5003bda87e93/CONTRIBUTING.md#d%C3%A9pannage)

2022-12-01 16:04 UTC, providenz approved these changes

2022-12-02 08:49 UTC, elishowk commented on CONTRIBUTING.md
> +BULK_INDEX_BATCH_SIZE=100
je mettrai bien aussi par défaut 100 ici https://github.com/MTES-MCT/trackdechets/blob/e4187500a5cb5d7acc3743eebbd959ba2d1fa8e1/back/src/bsds/indexation/bulkIndexBsds.ts#L540-L541

2022-12-02 08:49 UTC, elishowk requested changes
Merci, une suggestion proposée en commentaire sur https://github.com/MTES-MCT/trackdechets/blob/e4187500a5cb5d7acc3743eebbd959ba2d1fa8e1/back/src/bsds/indexation/bulkIndexBsds.ts#L540-L541

2022-12-05 08:41 UTC, GaelFerrand commented on CONTRIBUTING.md
> +BULK_INDEX_BATCH_SIZE=100
Bonne idée, done!

2022-12-05 10:15 UTC, merged