Update validation.ts
MTES-MCT/trackdechets pull request #1943
Opened 2022-12-06 11:29 UTC by chrischarousset

typo

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
- [ ] Informer le data engineer de tout changement de schéma DB
---

- [Ticket Favro]()

2022-12-06 12:43 UTC, GaelFerrand approved these changes

2022-12-06 12:46 UTC, Riron requested changes
En effet ça pète des tests back. Faudra qu'on corrige avant de merger

2022-12-07 15:11 UTC, GaelFerrand approved these changes

2022-12-20 14:39 UTC, providenz commented
Je ferme, repris dans https://github.com/MTES-MCT/trackdechets/pull/1994

2022-12-20 14:39 UTC, closed without merging