Corriger transporterCompanyVatNumber pour Form, 1 BSDA et 2 BSVHU suite à la correction faite sur `Company`
MTES-MCT/trackdechets pull request #1975
Opened 2022-12-14 11:12 UTC by elishowk

Corriger la base de données suite à la correction faite sur `Company`

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
- [ ] Informer le data engineer de tout changement de schéma DB
---

- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/95baff048704d6b9e0adbd28?card=tra-10485)

2022-12-14 12:26 UTC, Riron commented on back/prisma/scripts/fix-vatnumber-bsds.ts
> +      );
Avec 6K résultats, ça vous afficher un bon gros paquet d'infos. Je ne sais pas si ça a vraiment du sens du coup ?

2022-12-14 12:26 UTC, Riron commented on back/prisma/scripts/fix-vatnumber-bsds.ts
> +        where: { id: "BSDA-20220323-TXK0A50KQ" }
Ca ne marchera qu'en prod du coup ? Y'a rien à fixer sur les autres envs ? Vaudrait pas mieux faire une requete psql aussi ?
Idem pour les autres types de bordereaux.

2022-12-14 13:12 UTC, elishowk commented on back/prisma/scripts/fix-vatnumber-bsds.ts
> +        where: { id: "BSDA-20220323-TXK0A50KQ" }
Je pense que c'est plus secure de faire qu'en prod. S'il y a des différences en sandbox, on les règlera au cas par cas IMO.

2022-12-14 13:12 UTC, elishowk commented on back/prisma/scripts/fix-vatnumber-bsds.ts
> +      );
certes

2022-12-14 13:16 UTC, elishowk commented on back/prisma/scripts/fix-vatnumber-bsds.ts
> +        where: { id: "BSDA-20220323-TXK0A50KQ" }
ce sont 1 bsda + 2 bsvhu concernés, autant cibler

2022-12-14 13:20 UTC, elishowk commented on back/prisma/scripts/fix-vatnumber-bsds.ts
> +      );
j'ai remplacé par un log file

2022-12-14 14:04 UTC, Riron approved these changes

2022-12-14 14:19 UTC, elishowk commented on back/prisma/scripts/fix-vatnumber-bsds.ts
> +        where: { id: "BSDA-20220323-TXK0A50KQ" }
Oui la précaution est grosse. Cibler par "id", on on est sûr ce qui sera update.
Je limite à Form l'update en masse, je pense même logguer les anciennes valeurs VAT mal formatés dans le fichier log-clean-Form-transporterCompanyVatNumber.log"

2022-12-14 14:21 UTC, benoitguigal requested changes

2022-12-14 14:22 UTC, benoitguigal commented on back/prisma/scripts/fix-vatnumber-bsds.ts
> +          await prisma.form.update({
Auquel cas attention à ne pas écraser des n°SIRET avec n°TVA pour les entreprises françaises

2022-12-14 14:44 UTC, elishowk commented on back/prisma/scripts/fix-vatnumber-bsds.ts
> +        `select "id", "transporterCompanyVatNumber" from default$default."Form" as f where f."transporterCompanyVatNumber" ~ '(\\-|\\.|\\s)'`
Oui

2022-12-14 14:47 UTC, elishowk commented on back/prisma/scripts/fix-vatnumber-bsds.ts
> +          await prisma.form.update({
à la limite laisser les "transporterCompanySiret" tel quel (sachant qu'ils sont le doublon de "transporterCompanyVatNumber") ne pose pas de problème. On garde une trace du changement forcé de format de "transporterCompanyVatNumber", et on rgèle le problème initial du controle des permissions sur les BSDD (`permissions.ts`)

2022-12-14 14:49 UTC, elishowk commented on back/prisma/scripts/fix-vatnumber-bsds.ts
> +          await prisma.form.update({
oui, on pourra lancer un one-off `npm run reindex-all-bsds-bulk -- --useQueue --force`

2022-12-14 16:12 UTC, benoitguigal approved these changes

2022-12-14 16:39 UTC, elishowk commented on back/prisma/scripts/fix-vatnumber-bsds.ts
> +          await prisma.form.update({
Oui ajout fait ici https://github.com/MTES-MCT/trackdechets/pull/1975/files#diff-28994da7b68f45d1c069288672b37977815d8961d586350f0658b718094469fcR53

2022-12-14 16:39 UTC, elishowk commented on back/prisma/scripts/fix-vatnumber-bsds.ts
> +          await prisma.form.update({
Oui ajout fait ici https://github.com/MTES-MCT/trackdechets/pull/1975/files#diff-28994da7b68f45d1c069288672b37977815d8961d586350f0658b718094469fcR53

2022-12-15 09:49 UTC, benoitguigal approved these changes

2022-12-15 12:48 UTC, providenz approved these changes

2022-12-15 13:47 UTC, merged