API : il ne devrait pas être possible de valider un BSDD avec un SIRET qui est fermé selon l'insee
MTES-MCT/trackdechets pull request #2003
Opened 2022-12-28 16:44 UTC by elishowk

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
- [ ] Informer le data engineer de tout changement de schéma DB
---

- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/b64d96be58e6a57fe4d5c049?card=tra-8408)

2023-01-02 16:43 UTC, GaelFerrand commented on back/src/forms/resolvers/mutations/__tests__/markAsSealed.integration.ts
> +const searchCompanyMock = jest.spyOn(search, "default");
Nice

2023-01-02 16:44 UTC, GaelFerrand approved these changes

2023-01-23 09:37 UTC, providenz requested changes
La page companyInfos plante sur les établissements fermés
<img width="518" alt="Capture d’écran 2023-01-23 à 10 36 45" src="https://user-images.githubusercontent.com/878396/214007533-c70427ef-b261-4556-aca1-597e6d544786.png">

2023-01-23 09:44 UTC, providenz commented on back/src/forms/resolvers/mutations/markAsSealed.ts
> +    await checkForClosedCompanies(form.id);
Est-ce qu'on ne pourrait pas intégrer cette validation au beforeSignedByTransporterSchema ? si on a plusieurs erreurs sur le form, celle-ci n'apparaît que lorsqu'on a corrigé les autres.

2023-01-23 10:46 UTC, elishowk commented on back/src/forms/resolvers/mutations/markAsSealed.ts
> +    await checkForClosedCompanies(form.id);
L'idée ici : grouper tous les SIRET que faire un check d'un coup avec searchCompany qui est une requete externe potentiellement bloquante pour l'api. Comme c'est une requete externe on a bien besion de controler la concurrence, et pas laisser yup faire le contrôle un par un, ce qui risque d'être long

2023-01-23 15:49 UTC, elishowk commented on Changelog.md
> +- API : il n'est plus possible de créer un établissement ni de valider un BSDD avec un SIRET qui est fermé ou introuvable selon l'insee [PR 2003](https://github.com/MTES-MCT/trackdechets/pull/2003)
```suggestion
- Interdire la possibilité de créer un SIRET fermé selon l'INSEE, ni de valider ou re-valider (`markAsSealed` et `markAsResealed`) un BSDD avec un SIRET qui est fermé. Amélioration de l'affichage de la page publique `/company/1234` [PR 2003](https://github.com/MTES-MCT/trackdechets/pull/2003)
```

2023-01-23 16:25 UTC, providenz approved these changes
Nice

2023-01-24 08:21 UTC, merged