Adds a search on user companies list
MTES-MCT/trackdechets pull request #2057
Opened 2023-01-16 10:28 UTC by kornifex

[Uploading Screencast from 2023-01-16 11-25-56.webm…]()

- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-8795)

2023-01-23 14:05 UTC, providenz commented on front/src/account/AccountCompanyList.tsx
> +        listTitle = `${data.myCompanies?.totalCount} résultat${plural} pour la recherche: ${searchClue}`;
le totalCount est le nb total d'établissements associés et ne dépend pas du résultat de la recherche

2023-01-27 08:41 UTC, benoitguigal requested changes

2023-01-27 08:41 UTC, benoitguigal commented on back/src/users/typeDefs/user.queries.graphql
> +    search: String
S'agissant d'une query publique, ce serait bien ici de garder les conventions sur les filtres utilisées sur les bordereaux. Exemple sur la query `bsffs` => https://developers.trackdechets.beta.gouv.fr/reference/api-reference/bsff/queries#bsffs.

```
...
where: CompanyWhere 
....

input CompanyWhere {
  name: StringFilter 
  givenName: StringFilter
  orgId: StringFilter
  _and: CompanyWhere 
  _or: CompanyWhere 
  _not: CompanyWhere
}  
```

2023-02-09 16:07 UTC, providenz commented on back/src/users/typeDefs/user.queries.graphql
> +    search: String
L'idée c'était de faire un truc simple mais bon :)

2023-02-13 10:28 UTC, providenz commented on back/src/users/typeDefs/user.queries.graphql
> +    search: String
Dans un premier temps, on va passer ce paramètre en privé, même si  j'adhère à l'idée d'uniformiser, ça ne correspond pas à une demande api à ce jour.

2023-02-14 08:26 UTC, GaelFerrand commented on front/src/account/AccountCompanyList.tsx
> +  clue.length <= MAX_MY_COMPANIES_SEARCH;
Why not use Yup for input validation (on backend & frontend)?

2023-02-14 08:27 UTC, Riron approved these changes

2023-02-14 08:31 UTC, GaelFerrand approved these changes

2023-02-14 12:09 UTC, merged