add test to reproduce the error
MTES-MCT/trackdechets pull request #2382
Opened 2023-05-11 15:05 UTC by elishowk

# Cas d'un BSDA dont l'utilisateur est worker, transporter, destinataire, mais qui après signature producteur ne peut plus éditer le worker

![image](https://github.com/MTES-MCT/trackdechets/assets/76620/fafbcc1b-0328-4e63-a691-8afd27b2a1bc)

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
- [ ] Informer le data engineer de tout changement de schéma DB
---

- [Ticket Favro]()

2023-05-17 08:02 UTC, benoitguigal requested changes
Voir vidéo

2023-05-26 15:40 UTC, JulianaJM approved these changes

2023-05-30 08:01 UTC, benoitguigal commented
Tu as encore le problème sur les contenants : 

https://github.com/MTES-MCT/trackdechets/assets/2269165/736d7570-9109-45f0-9861-440d0c51b781

2023-05-30 08:04 UTC, benoitguigal approved these changes
Reste un problème sur les contenants

2023-05-30 12:41 UTC, elishowk commented
> Reste un problème sur les contenants
Oui le composant `Switch` non plus n'est pas désactivable

2023-05-31 09:34 UTC, merged