[TRA-11257] Auto-completion des récépissés Transporteurs Tous BSD
MTES-MCT/trackdechets pull request #2526
Opened 2023-07-01 13:59 UTC by elishowk

Reprise de #2402

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
- [ ] Informer le data engineer de tout changement de schéma DB
---

- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-11257)

2023-07-03 07:10 UTC, Riron requested changes
A mon sens, on ne devrait pas avoir d'update dans la partie parsing mais plutot utiliser les transformers comme c'est fait avec les sirets.

2023-07-03 07:10 UTC, Riron commented on back/src/bsda/validation/recipify.ts
> +    await prisma.bsda.update({
Selon moi ce n'est pas une bonne idée de faire un update à ce moment là. Le process de parsing / validation ne devrait pas avoir d'effet de bord comme ça. Ca rend le code plus complexe, et ce n'est pas le rôle de cette méthode.
Je comprend l'idée derrière, mais d'après moi dans le cas d'une signature il ne devrait pas y avoir de mise à jour du bordereau.
- si j'essaye de signer et que j'ai une erreur pour champ manquant, je dois mettre à jour mon bordereau
- notre front, dans le cas d'un BSDA, fait toujours un update avant de faire un sign. Donc dans le cas de notre UI l'utilisateur aura le même comportement que ce qui est fait ici.
- dans le cas d'une API, charge à eux de faire une update vide si nécessaire pour déclencher le mécanisme d'autocomplete qu'on met en place côté back

2023-07-03 07:10 UTC, Riron commented on back/src/bsda/validation/recipify.ts
> +export const recipify = async (bsda: Bsda, enableSaveTransporterReceipt) => {
`recipify` n'est pas hyper explicite comme nom.
Pour moi ce code devrait faire parti des transformers. `transporterReceiptTransformer` peut être ?

2023-07-07 11:52 UTC, benoitguigal commented
My 2 cents : 

Pour l'auto-complétion des raisons sociales et adresses, j'avais branché la fonction `sirenify` sur les inputs car il y a potentiellement beaucoup de n°SIRET sur chaque bordereau et je ne voulais pas déclencher des recherches ES intempestives à chaque update. 

Il me semble ici que le problème est un peu différent car on a à priori beaucoup moins de transporteurs présents sur le bordereau et les données sont en base. Pour factoriser un peu le code, j'aurais plutôt tendance à déplacer la logique d'auto-complétion au niveau du repository. Dans la méthode d'update du repository, on pourrait faire l'auto-complétion uniquement si le transporteur a changé à mon avis. 

Par ailleurs il me semble que la mise à jour des infos du récépissés lors des étapes de signature que tu as implémenté vise à ce que les infos récépissé du bordereau reste à jour dans le cas où un transporteur aurait modifié son récépissé entre le moment où le bordereau a été crée et le moment de la signature. À mon sens il vaudrait mieux avoir un hook asynchrone lorsqu'un transporteur modifie son récépissé qui va modifier tous les bordereaux dont il est le transporteur et qui ne sont pas encore au statut SENT (en ajoutant au passage un petit log de statut et une réindexation pour qu'on puisse tracer et mettre à jour l'UI). 

Pour aller encore plus loin, j'aurais peut-être vu les choses encore différemment avec une version semi-normalisée (désolé je n'y pense que maintenant je n'avais pas eu le temps de me pencher sérieusement sur cette PR avant), à garder peut-être en tête pour la suite : 
- Créer une relation entre les bordereaux et la table `TransporterReceipt` (pour le BSDD ce serait entre la table `BsddTransporter` et la table `TransporterReceipt`).
- Lorsqu'un transporteur modifie son récépissé, on en crée un nouveau plutôt que de modifier l'existant (on pourrait même en créer un nouveau uniquement si le numéro change et le modifier directement en cas d'extension de la date de validité). Les bordereaux archivés pointent donc toujours sur les anciens récépissés. 
- Mettre à jour avec un hook tous les identifiants de récépissés des bordereaux qui n'ont pas encore été pris en charge par le transporteur. 
 
À ta dispo pour en discuter et éventuellement te filer un coup de main.

2023-07-11 08:58 UTC, benoitguigal commented on back/src/bsda/validation/validate.ts
> +      if (validationContext.enableCompletionTransformers) {
@Riron a un hotfix en cours là dessus pour ne pas jouer le sirenify sur les champs déjà verrouillés. Peut-être qu'il y aura un petit conflit.

2023-07-11 08:58 UTC, benoitguigal commented on back/src/bsdasris/resolvers/mutations/__tests__/updateBsdasri.integration.ts
> +    // expect(data.updateBsdasri.transporter!.recepisse).toEqual(null);
code commenté

2023-07-11 08:58 UTC, benoitguigal commented on back/src/forms/validation.ts
> +      .when(["transporterIsExemptedOfReceipt", "transporterCompanyVatNumber"], {
Je ne vois pas de tests sur `signTransportForm` qui vérifie cette validation

2023-07-11 09:01 UTC, elishowk commented on back/src/bsda/validation/validate.ts
> +      if (validationContext.enableCompletionTransformers) {
@Riron pourras-tu m'aider pour le rebase ?

2023-07-11 09:09 UTC, elishowk commented on back/src/bsdasris/resolvers/mutations/__tests__/updateBsdasri.integration.ts
> +    // expect(data.updateBsdasri.transporter!.recepisse).toEqual(null);
```suggestion
```

2023-07-11 09:09 UTC, elishowk commented on back/src/forms/validation.ts
> +      .when(["transporterIsExemptedOfReceipt", "transporterCompanyVatNumber"], {
Je note et m'en occupe dès que c'est en recette

2023-07-11 11:56 UTC, kornifex approved these changes
Ok pour le front

2023-07-11 13:03 UTC, GaelFerrand approved these changes

2023-07-11 13:55 UTC, benoitguigal approved these changes

2023-07-11 16:45 UTC, merged