[Bugfix] Le CompanySelector devrait se souvenir des informations concernant l'entreprise sélectionnée
MTES-MCT/trackdechets pull request #2586
Opened 2023-07-24 09:31 UTC by GaelFerrand

# Contexte

Dans le CompanySelector, si je sélectionne une entreprise, change de page, puis revient, puis coche/décoche l'entreprise précédemment sélectionnée, les données disparaissent.

Le données devraient persister. A noter, contrairement à ce que le ticket Favro stipule, cela arrive pour tous les bordereaux.

# Démo

![company_selector_bug](https://github.com/MTES-MCT/trackdechets/assets/45355989/a8605419-6b82-43e1-b803-f732752f7381)

# Ticket Favro

[Le numéro d'agrément devrait être automatiquement ajouté sur le BSVHU s'il a bien été renseigné dans Mon compte. ](https://favro.com/widget/ab14a4f0460a99a9d64d4945/b34d77951d96c0ad27b28f5a?card=tra-11394)

2023-07-24 09:40 UTC, GaelFerrand commented on front/src/form/common/components/company/CompanySelector.tsx
> +
Si ma compréhension du bug est correcte, quand on change d'onglet dans la création d'un BSD, aucune donnée ne persiste dans le `CompanySelector`. Donc il essaie de reconstruire la liste des companies en allant chercher les favorites, et en regardant les données dans Formik. Il semblerait que ces données soient insuffisantes ou mal utilisées. 

Bref, pour la company séléctionnée au moins que retourne chercher l'objet complet auprès du backend. Si GQL est bien configuré la query devrait utiliser la cache et ne même pas appeler le backend.

2023-07-24 10:45 UTC, benoitguigal approved these changes

2023-07-24 11:30 UTC, GaelFerrand commented on front/src/form/common/components/company/CompanySelector.tsx
> +  }, [searchCompaniesQuery, siret, field.value]);
Done

2023-07-24 11:30 UTC, GaelFerrand commented on front/src/form/common/components/company/CompanySelector.tsx
> +    if (field.value.orgId) {
Done

2023-07-24 11:54 UTC, elishowk commented on front/src/form/common/components/company/CompanySelector.tsx
> +  }, [searchCompaniesQuery, siret, field.value?.orgId]);
```suggestion
  }, [searchCompaniesQuery, field.value?.orgId]);
```

2023-07-24 11:56 UTC, elishowk commented on front/src/form/common/components/company/CompanySelector.tsx
> +  }, [searchCompaniesQuery, siret, field.value?.orgId]);
Voir useMemo ci-dessous qui maintient la compatibilité avec les usages de CompanySelector là où il n'y a pas d'orgId, càd pour les Intermédiaires BSDD et BSDA.

2023-07-24 13:10 UTC, elishowk requested changes
Si on ajoute e useEffect, pourquoi ne pas supprimer ce qui apparait comme doublon pour la query companyPrivateInfos juste en desssous ?

2023-07-28 14:18 UTC, GaelFerrand commented on front/src/form/common/components/company/CompanySelector.tsx
> +  }, [searchCompaniesQuery, siret, field.value?.orgId]);
Je crois que Benoit a essayé cette technique mais n'a pas réussi à la faire marcher 

https://mattermost.incubateur.net/fabnum-mte/pl/mb54jfqng7ydzb1ge5atkcxs7r

2023-07-31 14:23 UTC, elishowk requested changes
avec l'ajout du useEffect, on devrait supprimerd une autr bout de code "companyPrivateInfos" plus haut. Sinon on risque des effets secondaires à cette modif qui créeront d'autres bugs potentiellement.

2023-07-31 15:18 UTC, providenz commented
Le pb me paraît pas critique, le composant est à peu près stable et on est en effectif réduit, on va reporter la mep de cette PR

2023-08-18 10:53 UTC, elishowk commented on front/src/form/common/components/company/CompanySelector.tsx
> +
IMO Ce fix n'est pas complet et créé une requete inutile. Le probleme vient d'un mauvais type de retour sur companyPrivateInfos qui est requêtée dès le chargement de la page

2023-08-21 07:47 UTC, elishowk commented
Bug fixé dans https://github.com/MTES-MCT/trackdechets/pull/2633

2023-08-21 07:47 UTC, closed without merging