[TRA-13282] Entreprise Anonyme : Simplifier le processus de création d'un établissement non diffusible
MTES-MCT/trackdechets pull request #3096
Opened 2024-02-15 16:59 UTC by GaelFerrand

# Contexte

# Démo

# Ticket Favro

[Entreprise Anonyme : Simplifier le processus de création d'un établissement non diffusible](https://favro.com/widget/ab14a4f0460a99a9d64d4945/812f76c7447d8c51e7511056?card=tra-13282)

2024-02-28 13:17 UTC, GaelFerrand commented on back/src/companies/geo/getCodeCommune.ts
> +import axios from "axios";
Petit fichier avec getCodeCommune, qui appelle [cette API](https://adresse.data.gouv.fr/api-doc/adresse). A priori très simple, pas besoin de s'authentifier, pas de rate limit, dans tous les cas on devrait l'appeler ~10/20 fois par jour, donc pas énorme.

Par contre, pour une adresse donnée il arrive que l'API retourne plusieurs codeCommune. Pour le moment je prends le premier. Les admins pourront de toute façon contre-vérifier avant de créer l'entreprise anonyme.

2024-02-28 13:19 UTC, GaelFerrand commented on back/src/companies/resolvers/Mutation.ts
>  import createAnonymousCompany from "./mutations/createAnonymousCompany";
Cette PR introduit 2 nouvelles mutations:
- `createAnonymousRequest`: l'utilisateur upload son PDF et demande à ce que son établissement non-diffusible soit créé dans notre DB
- `deleteAnonymousCompanyRequest`: un admin peut supprimer une requête

2024-02-28 13:20 UTC, GaelFerrand commented on back/src/companies/resolvers/Query.ts
>  import favorites from "./queries/favorites";
Cette PR introduit 2 nouvelles queries:
- anonymousCompanyRequests: pour récupérer les demandes de création d'entreprise anonyme en cours (paginé)
- anonymousCompanyRequest: pour récupérer une demande (par siret)

2024-02-28 13:23 UTC, GaelFerrand commented on back/src/companies/resolvers/mutations/createAnonymousCompany.ts
> -    vatNumber: foreignVatNumber,
Vu avec l'équipe support: on ne crée jamais d'entreprise anonyme avec un numéro de TVA, donc je l'ai arraché. Le SIRET est donc obligatoire dans tous les cas.

Par contre je n'ai pas supprimé la colonne `vatNumber` en DB parce qu'on a ~600 entreprises anonymes avec un numéro de TVA. Probablement du vieux legacy.

2024-02-28 13:25 UTC, GaelFerrand commented on back/src/companies/resolvers/mutations/createAnonymousCompany.ts
> +    // If there was an anonymousCompanyRequest associated, delete it and warn the user
2 façons de créer une entreprise anonyme:
- Un utilisateur a initié la requête avec un PDF: auquel cas, une fois l'entreprise créée on supprime la demande et on lui envoie un mail
- L'admin part de zéro et renseigne tous les champs manuellement

On supprime les demandes parce qu'elles contiennet le PDF, ce qui pourrait rapidement faire grossir la DB (compter environ ~300/400Ko). Vu avec Laurent

2024-02-28 13:28 UTC, GaelFerrand commented on back/src/companies/resolvers/mutations/createAnonymousCompanyRequest.helpers.ts
> +import pdfParser from "pdf-parse";
Ce fichier contient plein de méthodes utilitaires liées à l'exploitation du PDF, telles que:
- Convertir le PDF en base64, en texte exploitable
- Vérifier autant que possible qu'il provient bien de la base SIRENE
- Extraire les différentes données dont on a besoin (nom de l'entreprise, SIRET etc.)
- Faire des vérifications sur l'entreprise (pas fermée)

J'utilise [pdf-parse](https://www.npmjs.com/package/pdf-parse) pour parser le PDF, et la soupe qui en sort est très "brute", c'est pas un beau JSON. Donc je prends un maximum de précautions, mais la feature est vulnérable: si la base SIRENE change son format de PDF, ça cassera. J'ai prévu un fallback que j'explique plus loin.

2024-02-28 13:33 UTC, GaelFerrand commented on back/src/companies/resolvers/mutations/createAnonymousCompanyRequest.helpers.ts
> +  if (looksHacky(JSON.stringify({ text, info, metadata }))) {
J'ai introduis quelques tentatives de checks de sécurité, mais honnêtement c'est plutôt faible puisque je vérifie le texte parsé, or souvent le code malfaisant est dans le code non parsé du PDF. J'en reparle plus bas.

2024-02-28 13:34 UTC, GaelFerrand commented on back/src/companies/resolvers/mutations/createAnonymousCompanyRequest.ts
> +const createAnonymousCompanyRequestResolver: MutationResolvers["createAnonymousCompanyRequest"] =
ça c'est la mutation pour créer une `anonymousCompanyRequest`. Elle prend un pdf en base64, et un siret en entrée. Le siret permet de s'assurer que l'utilisateur upload bien un PDF qui correspond au SIRET qu'il a renseigné dans le formulaire de création d'entreprise.

2024-02-28 13:36 UTC, GaelFerrand commented on back/src/companies/resolvers/mutations/deleteAnonymousCompanyRequest.ts
> +const deleteAnonymousCompanyRequestResolver: MutationResolvers["deleteAnonymousCompanyRequest"] =
On donne la possibilité aux admins de supprimer une demande. Pas hyper utilisé je pense, mais ça peut être pratique pour tester en recette, ça permet de rejouer les tests sur les même entreprises.

2024-02-28 13:41 UTC, GaelFerrand commented on back/src/companies/resolvers/queries/anonymousCompanyRequest.ts
> +export const anonymousCompanyRequestResolver: QueryResolvers["anonymousCompanyRequest"] =
Query qui permet de récupérer une `anonymousCompanyRequest`. On requête avec le `siret` et pas l'`id`, parce que sur le formulaire de création d'entreprise on veut pouvoir savoir si une requête existe déjà pour l'entreprise visée, or on n'a qu'un SIRET:
![image](https://github.com/MTES-MCT/trackdechets/assets/45355989/a0e2d19a-c137-4a15-bb7c-a1954c8afea1)

2024-02-28 13:42 UTC, GaelFerrand commented on back/src/companies/resolvers/queries/anonymousCompanyRequests.ts
> +export const anonymousCompanyRequestsResolver: QueryResolvers["anonymousCompanyRequests"] =
Query pour récupérer les `anonymousCompanyRequests` paginée. Utilisée sur le dashboard admin pour afficher toutes les demandes en cours.

2024-02-28 13:43 UTC, GaelFerrand commented on back/src/companies/typeDefs/private/company.inputs.graphql
> -  vatNumber: String
Comme expliqué plus haut, j'arrache le `vatNumber`

2024-02-28 13:44 UTC, GaelFerrand commented on back/src/companies/typeDefs/private/company.objects.graphql
> +  user: AnonymousCompanyRequestUser!
Les admins veulent pouvoir écrire facilement à la personne qui a initié la demande de création d'entreprise anonyme, donc micro jointure sur le champ email:
![image](https://github.com/MTES-MCT/trackdechets/assets/45355989/e51a6a96-1689-4bc7-887b-3c7f7f5246ab)

2024-02-28 13:45 UTC, GaelFerrand commented on back/src/server.ts
> +      createAnonymousCompanyRequest: {
Petite mesure de sécurité pour éviter qu'un utilisateur remplisse notre DB de requêtes. Comme chaque requête contient un PDF en base64 d'environ 300/400Ko, ça peut vite grossir.

2024-02-28 13:46 UTC, GaelFerrand commented on back/src/server.ts
> +app.use(json({ limit: "1mb" }));
Du coup pour pouvoir uploader les PDF j'ai dû augmenter la limite. Je pense qu'avec 1mb on est larges. Si ça pose problème dites-le moi.

2024-02-28 13:49 UTC, GaelFerrand commented on back/src/server.ts
> +    httpOnly: true,
L'upload de PDF pose des challenges en terme de sécurité (j'en reparle plus bas), du coup je suis tombé sur ça, et je suggère de passer les cookies en `httpOnly` ([explication du flag par OWASP](https://owasp.org/www-community/HttpOnly)).

Globalement c'est une excellente mesure de sécurité qui mange pas de pain. Dites-moi si ça pose problème. Il se peut que je mesure pas les conséquences de ce paramétrages, qui a peut-être déjà fait débat

2024-02-28 13:50 UTC, GaelFerrand commented on back/src/utils.ts
> +export const looksHacky = (str: string): boolean => {
Petite méthode qui essaie de détecter les gros hacks obvious. Ce n'est en aucun cas une barrière robuste ni ultime, mais j'essaie de faire ce qui est possible.

Utilisée pour vérifier le contenu parsé des PDF.

2024-02-28 13:53 UTC, GaelFerrand commented on front/src/Apps/utils/fileUtils.ts
> +// https://stackoverflow.com/questions/13538832/convert-pdf-to-a-base64-encoded-string-in-javascript
Lorsque l'utilisateur crée une demande de création d'entreprise anonyme, il doit fournir une PDF d'avis de situation SIRENE. L'implémentation logique est de mettre en place du file upload, ce qui n'est pas branché dans notre API en l'état.

ça pose plusieurs problèmes:
- Premièrement, c'est chiant à mettre en place
- ça nous oblige à utiliser un service tiers payant de type S3 pour stocker les PDF

La galipette ici consiste à convertir les PDF en base64 et à les envoyers à l'API sous forme de string, puis de les sauvegarder en tant que string dans la DB. ça fonctionne bien et ça ne nécessite rien de particulier, si ce n'est d'augmenter la taille limite des requêtes acceptée.

Côté front ça marche très bien aussi: l'outil de visualisation côté admin peut naturellemen travailler avec du base64.

2024-02-28 13:55 UTC, GaelFerrand commented on front/src/Apps/utils/utils.ts
> +/**
Petite méthode utilitaire pour extraire le code postal d'une adresse, ce qui pemettra d'aller chercher le codeCommune associé.

2024-02-28 13:57 UTC, GaelFerrand commented on front/src/account/accountCompanyAdd/anonymous/AccountCompanyAddAnonymousCompany.tsx
> +const DISABLE_FILE_UPLOAD =
Comme expliqué plus haut, si la base SIRENE change le format de ses PDF, on est eus. Donc je mets ce flag dans les vars d'env, pour pouvoir n'importe quand désactiver la feature complètement. Auquel cas les utilisateurs devront passer par le support, comme ils font jusqu'à aujourd'hui.

2024-02-28 13:59 UTC, GaelFerrand commented on front/src/account/accountCompanyAdd/anonymous/AccountCompanyAddAnonymousCompany.tsx
> +      <Upload
L'input pour uploader le PDF. Comme expliqué plus haut, on récupère le fichier, on vérifie que c'est un PDF, puis on le convertit en base64 avant de l'envoyer au backend.

2024-02-28 14:01 UTC, GaelFerrand commented on front/src/admin/anonymousCompany/AnonymousCompaniesDashboard.tsx
> +import { AnonymousCompaniesRequests } from "./AnonymousCompaniesRequests";
Dashboard admin, qui permet:
- D'afficher toutes les demandes 
- De valider une demande
- De créer une entreprise from scratch

2024-02-28 14:02 UTC, GaelFerrand commented on front/src/admin/anonymousCompany/AnonymousCompaniesRequests.tsx
> +import { gql, useMutation, useQuery } from "@apollo/client";
Tableau des demandes:
![image](https://github.com/MTES-MCT/trackdechets/assets/45355989/b2c8a395-e522-40b3-9885-de237b930ee0)

Pour celui-là je suis parti de zéro avec la `Table` et la `Pagination` du dsfr, c'est très simple, assez intuitif et ça marche bien.

2024-02-28 14:03 UTC, GaelFerrand commented on front/src/admin/anonymousCompany/AnonymousCompaniesRequestsPagination.tsx
> +import Pagination from "@codegouvfr/react-dsfr/Pagination";
Petit wrapper du seigneur autour du `Pagination` du dsfr, qui au-delà de la couche UI, gère les calls API.

Le truc est codé pour fonctionner avec n'importe quelle query qui a du `first` et du `skip`, donc on peut peut-être le rendre générique et le ré-utiliser ailleurs.

2024-02-28 14:06 UTC, GaelFerrand commented on front/src/admin/anonymousCompany/CodeCommuneLinks.tsx
> +import * as React from "react";
Petit outil pour permettre aux admins de facilement vérifier si un codeCommune est correcte (ça leur facilite le googling quoi):
![image](https://github.com/MTES-MCT/trackdechets/assets/45355989/2a22d988-0bdf-4642-aa68-a84e31a7e449)

Etant donné que les URLs contiennent des données fournies par l'utilisateur, elles sont potentiellement hackables (XSS),mais ça devrait être safe puisqu'elles ne contiennent que le code postal, qui est extrait via une régex.

2024-02-28 14:08 UTC, GaelFerrand commented on front/src/admin/anonymousCompany/CreateAnonymousCompany.tsx
> -import * as React from "react";
ça c'est le formulaire pour créer une entreprise anonyme. Il existait déjà, j'ai juste ajouté:
- Si la demande vient de l'utilisateur:
  - L'affichage du PDF
  - La pré-complétion des champs
  - Les outils de recherche rapide pour le codeCommune
- Si l'admin part de zéro:
  - Les outils de recherche rapide pour le codeCommune

2024-02-28 14:08 UTC, GaelFerrand commented on front/src/admin/anonymousCompany/CreateAnonymousCompany.tsx
> +          <CreateAnonymousCompanyForm
Pour plus de clarté j'ai sorti le form dans un fichier à part

2024-02-28 14:08 UTC, GaelFerrand commented on front/src/admin/anonymousCompany/CreateAnonymousCompany.tsx
> +            <PDFViewer pdf={data?.anonymousCompanyRequest.pdf} />
Le composant qui affiche le PDF

2024-02-28 14:13 UTC, GaelFerrand commented on front/src/admin/anonymousCompany/PDFViewer.tsx
> +import React from "react";
ça c'est le composant qui affiche le PDF côté client, à l'admin. A noter, je n'ai utilisé aucune lib, c'est du natif. C'est peut-être pas supporté par tous les navigateurs mais osef puisque c'est pour nous.

:warning:  GROS POINT DE VIGILANCE :warning: 

On laisse l'utilisateur uploader un PDF qu'on affiche directement à l'admin! ça pose donc un gros souci potentiel de sécurité!
J'essaie côté API de mettre quelques protections en place, mais qui sont clairement insuffisantes. Donc tout repose sur la balise `<object>`. D'après mes recherches, c'est un outil raisonnablement safe, mais qui a été exploité par le passé. 

Si on veut être plus safe, on peut mettre en place une vérification côté API avec par exemple PDFID ou AnalyzePDF, mais ce sont des librairies qui n'existent qu'en python. A voir quelle est la façon la plus simple de les brancher.

2024-02-28 14:15 UTC, GaelFerrand commented on libs/back/mail/src/templates/index.ts
> +export const createAnonymousCompanyRequestEmail: MailTemplate<{
Deux nouveaux emails:
- Quand l'utilisateur crée se demande de création d'entreprise anonyme, pour lui dire qu'elle bien été créée
- Quand l'admin la valide, pour dire à l'utilisateur d'aller créer son entreprise

2024-02-28 14:17 UTC, GaelFerrand commented on package.json
> +    "pdf-parse": "^1.1.1",
La seule nouvelle librairie, qui permet de parser les PDF.

2024-02-28 14:18 UTC, GaelFerrand commented on back/src/companies/resolvers/mutations/createAnonymousCompanyRequest.helpers.ts
> +      pdfParser(buffer)
Le seul endroit où j'utilise la lib `pdf-parse`

2024-02-28 16:35 UTC, GaelFerrand commented on front/src/admin/anonymousCompany/AnonymousCompaniesRequests.tsx
> +      <div className={styles.textCenter}>
Pour faciliter le travail au support, sous l'email il y a 2 icônes, une qui permet de copier/coller l'adresse mail, et une autre qui ouvre un ticket dans Zammad. J'ai pas trouvé mieux dans le temps imparti (vu avec Anne-Sophie)

![image](https://github.com/MTES-MCT/trackdechets/assets/45355989/c368821e-0e12-4460-a759-78f8b97d9cac)

2024-03-01 07:55 UTC, GaelFerrand commented on front/src/Apps/utils/utils.ts
> +export const copyToClipboard = async (textToCopy: string) => {
Petite méthode utilitaire pour copier du texte dans le presse-papier. Plus touchy que ça n'en a l'air, notamment le bête `navigator.clipboard.writeText` ne fonctionne pas pour les domaines qui sont pas en https

2024-03-01 07:57 UTC, GaelFerrand commented on back/src/common/validation.ts
> +export const base64 = yup
Utiliaire Yup pour la validation d'un base64

2024-03-01 08:14 UTC, GaelFerrand commented on back/src/companies/geo/getCodeCommune.ts
> +    const sanitizedAddress = removeSpecialChars(address);
A noter ici on a une injection potentielle dans le champ `address`, donc je vire tous les caractères spéciaux.

2024-03-01 09:26 UTC, elishowk commented on back/src/companies/resolvers/mutations/createAnonymousCompany.ts
> -    vatNumber: foreignVatNumber,
`vatNumber` devrait rester car il a été rajouté récemment afin de palier aux errements de la base VIES : si une entreprise étrangère n'est pas visible sur VIES, on fallback sur une entreprise anonyme. Et ça peut arriver souvent...

![image](https://github.com/MTES-MCT/trackdechets/assets/76620/3b15f805-9ed8-47b8-ad12-31578588aec3)

2024-03-01 09:27 UTC, elishowk commented on back/src/companies/typeDefs/private/company.inputs.graphql
> -  vatNumber: String
il ne vaut mieux pas, c'est notre seul moyen de rattraper l'api VIES qui ne donne parfois pas la confirmation de l'existence d'un boite intra-communautaire.

2024-03-01 09:31 UTC, elishowk commented on front/src/Apps/utils/fileUtils.ts
> +// https://stackoverflow.com/questions/13538832/convert-pdf-to-a-base64-encoded-string-in-javascript
ça empêche de visualiser les PDF ensuite, non ? ça ne pose pas problème en cas de vérification manuelle ?

2024-03-01 09:34 UTC, elishowk requested changes
IMO il faut garder la possibilité de créer des entreprises étrangères

2024-03-01 09:34 UTC, elishowk commented on front/src/Apps/utils/utils.ts
> +export const copyToClipboard = async (textToCopy: string) => {
Je verrais bien tous ces commentaires github intégrés en JSDoc des fonctions concernées, non ?

2024-03-01 14:55 UTC, GaelFerrand commented on back/src/companies/resolvers/mutations/createAnonymousCompany.ts
> -    vatNumber: foreignVatNumber,
Comme discuté avec Elias & Marion, j'ai remis le vatNumber puisqu'apparemment on se sert de cette feature pour enregistrer des entreprises étrangères non connues du VIES (un peu un hack mais seul recours actuel)

2024-03-04 12:26 UTC, GaelFerrand commented on front/src/Apps/utils/fileUtils.ts
> +/**
Méthode utilisée côté front pour convertir le PDF en base64 avant de l'envoyer à l'API.

2024-03-04 12:29 UTC, GaelFerrand commented on front/src/admin/anonymousCompany/CreateAnonymousCompanyForm.tsx
> +import * as React from "react";
Du coup comme discuté avec Elias il contiendra aussi le numéro de TVA

2024-03-04 12:50 UTC, Riron reviewed
Le petit Jésus du support.
Beau boulot !

2024-03-04 12:50 UTC, Riron commented on libs/back/prisma/src/migrate/migrations/171_anonymousCompanyRequest.sql
> +CREATE UNIQUE INDEX IF NOT EXISTS "AnonymousCompanyRequest_pkey" ON "default$default"."AnonymousCompanyRequest" ("id");
Pour info, dans la mesure ou "id" est déjà défini comme Primary key plus haut, Postgresql crée automatiquement un index unique dessus. Cette déclaration n'est donc pas nécessaire

2024-03-04 12:50 UTC, Riron commented on back/src/companies/resolvers/mutations/createAnonymousCompanyRequest.ts
> +    if (data.siret !== siret) {
On est certain que le document que tu parses (avis de situation sirene donc) est le seul et unique document recevable ?
Et quid d'un document scanné par exemple ?
J'ai peur qu'avec un check aussi strict, beaucoup de cas ne rentrent pas dans ce beau process.
Est-ce qu'on accepterait pas le document de toute façon, et on fait le prefill des champs à la volée lorsqu'on y arrive sur la page d'admin au lieu de le faire en amont et de le persister en base ?

Il y a un trade off entre le support le prend de mauvais docs à traiter VS des utilisateurs n'arrivent pas à envoyer leur justificatif et contactent le support

2024-03-04 12:50 UTC, Riron commented on back/src/companies/typeDefs/company.mutations.graphql
> +  deleteAnonymousCompanyRequest(siret: String!): Boolean
Ca devrait être dans le sous répertoire `/private` je pense ça. Ces queries & mutations n'ont pas vocation à être publiques (=utilisées par des intégrateurs tiers)

2024-03-04 13:18 UTC, GaelFerrand commented on libs/back/prisma/src/migrate/migrations/171_anonymousCompanyRequest.sql
> +CREATE UNIQUE INDEX IF NOT EXISTS "AnonymousCompanyRequest_pkey" ON "default$default"."AnonymousCompanyRequest" ("id");
Je corrige

2024-03-04 13:28 UTC, GaelFerrand commented on back/src/companies/resolvers/mutations/createAnonymousCompanyRequest.ts
> +    if (data.siret !== siret) {
C'est une bonne remarque qui a été longuement débattue. Je crois qu'on va essayer avec un mode strict pour rendre le processus plus rapide pour tout le monde dans un premier temps, mais les filles vont suivre son utilisation et voir si c'est opti.

Personnellement j'ai défendu le côté strict, parce que:
- Sur n'importe quel site genre URSSAF, CAF etc., ils demandent des justificatifs précis à fournir, on n'est pas les premiers à demander ça. Tout entrepreneur est habitué à ce genre de demande
- L'info est facilement accessible, d'autant qu'on leur remet le lien
- Autoriser d'uploader n'importe quoi, c'est hasardeux. Rien qu'en terme de poids, entre un PDF et un scan, la taille fait x4 facilement. Et on s'expose à davantage de failles de sécurité (sans parler du fait qu'on n'a pas vraiment amélioré le process). 
- Si les gens upload souvent des trucs pas exploitables, finalement l'équipe US devra se farcir des échanges de mails, autant partir directement de Zammad dans ce cas-là

Donc je pense qu'on va voir avec la pratique. Après honnêtement au moindre souci il y a un message d'erreur avec le contact du support, donc 0% de chance pour que quelqu'un soit bloqué indéfiniment sur cette page.

Il y aura surement quelques irréductibles, mais si déjà 80% des cas sont traités en 2s...

2024-03-04 13:42 UTC, Riron approved these changes

2024-03-04 16:03 UTC, elishowk approved these changes

2024-03-04 16:09 UTC, merged