Amélioration de l'impersonation
MTES-MCT/trackdechets pull request #3197
Opened 2024-03-20 09:53 UTC by Riron

Suite à des discussions lors du séminaire

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
- [ ] Informer le data engineer de tout changement de schéma DB
---

- [Ticket Favro]()

2024-03-27 08:38 UTC, providenz approved these changes
La classe !

2024-03-27 08:40 UTC, providenz commented on front/src/admin/user/impersonate.tsx
> +          <form action={`${VITE_API_ENDPOINT}/impersonate`} method="post">
On a un form nested

2024-03-28 10:41 UTC, benoitguigal requested changes
Top ça va être super pratique.
En revanche vu la criticité de ce code, il manque à mon sens des tests pour le endpoint `/impersonate` et pour le middleware

2024-03-28 13:24 UTC, benoitguigal commented on back/src/routers/__tests__/auth-router.integration.ts
> +    it("should return 500 if user is admin and impersonated user is not found", async () => {
```suggestion
    it("should return 400 if user is admin and impersonated user is not found", async () => {
```

2024-03-28 13:25 UTC, benoitguigal approved these changes

2024-03-28 13:58 UTC, merged