Script de nettoyage des évènements Mongo
MTES-MCT/trackdechets pull request #3293
Opened 2024-05-03 08:08 UTC by Riron

Script pour nettoyer les évènements consécutifs identiques.
On a des bordereaux avec jusqu'à 263K events associés

2024-05-10 13:13 UTC, GaelFerrand approved these changes
Curieux de voir à quel point ça va réduire la DB

2024-05-15 07:15 UTC, benoitguigal requested changes

2024-05-15 07:15 UTC, benoitguigal commented on back/src/scripts/bin/cleanMongoEvents.helper.ts
> +    cursor = bsds[bsds.length - 1]?.id;
Dans la requête au dessus tu trie par `rowNumber` mais ici tu passes l'`id` en curseur.

2024-05-15 08:08 UTC, benoitguigal commented
Est-ce qu'on a traité le problème à la source sur tous les bordereaux ?

2024-05-15 08:46 UTC, Riron commented
> Est-ce qu'on a traité le problème à la source sur tous les bordereaux ?

Non pas encore. Seul le BSDA est protégé je crois.
Ca serait bien d'assez vite traiter ce problème. Ca viendrait probablement avec une refonte de la validation, ce n'est donc pas anodin comme modif. A moins de faire un truc différent temporaire mais plus rapide

2024-05-28 07:04 UTC, providenz approved these changes

2024-06-27 11:42 UTC, benoitguigal approved these changes

2024-06-28 12:23 UTC, merged