[tra-13295] Retirer la dépendance avec MongoDB pour les révisions
MTES-MCT/trackdechets pull request #3411
Opened 2024-06-19 13:21 UTC by Riron

On stocke un snapshot du bsd directement dans la révision

- [ ] Mettre à jour la documentation
- [ ] Mettre à jour le change log
- [ ] Documenter les manipulations à faire lors de la mise en production (sur le ticket Favro de release)
- [ ] S'assurer que la numérotation des nouvelles migrations est bien cohérente
- [ ] Informer le data engineer de tout changement de schéma DB
---

- [Ticket Favro](https://favro.com/organization/ab14a4f0460a99a9d64d4945/2c84e07578945e0ee8fb61f3?card=tra-13295)

2024-06-21 14:34 UTC, silto approved these changes
Je suppose que tu t'es posé la question, mais pourquoi ne pas avoir une table pour les snapshots (une par type de bordereau du coup) plutôt que les mettre dans des JSON?
De ce que je vois:
Arguments en faveur du JSON:
- pas besoin de s'embêter à migrer les snapshots quand le modèle de bordereau évolue
- facile d'accès depuis la revisionRequest
Arguments en faveur de tables:
- pas de problème de rétrocompatibilité en cas de snapshot datant d'avant une modif de model
- requêtes plus légères si on fait des queries sur revisionRequest qui n'ont pas besoin du snapshot

2024-06-21 14:34 UTC, silto commented on back/src/bsdasris/resolvers/mutations/revisionRequest/createRevisionRequest.ts
> +    bsdasriSnapshot: JSON.stringify(bsdasri)
Tu utilises un stringify ici alors que tu ne le fais pas pour le BSDA. L'un et l'autre sont ok (c'est fait par prisma de toute façon) mais si ça peut être pareil partout c'est mieux je pense

2024-06-24 15:10 UTC, providenz approved these changes

2024-06-25 08:51 UTC, benoitguigal requested changes

2024-06-25 08:51 UTC, benoitguigal commented on back/src/forms/resolvers/FormRevisionRequest.ts
> +      bsddSnapshot: PrismaFormWithForwardedInAndTransporters;
Je trouve très casse-gueule cette histoire de stockage en `Json`, c'est à peu près certain que `expandFormFromDb(parent.bsddSnapshot)` ci-dessous va péter au moindre changement de schéma Prisma. Je trouverai ça beaucoup plus safe d'ajouter sur `BsddRevisionRequest` des colonnes avec pour chaque champ révisable la valeur avant révision : `initialRecipientCap`, `initialWasteDetaisCode`, `initialWasteDetailsPop`, etc.

On aurait ensuite juste à récupérer ces valeurs : 

```typescript
const initialForm = {
  recipientCap: revision.initialRecipientCap;
  ....
}

return expandFormFromDb({
   ...currentForm,
   ...initialForm
})
```

2024-09-17 09:31 UTC, merged