Enhance logger
MTES-MCT/trackdechets pull request #3415
Opened 2024-06-20 14:48 UTC by Riron

Amélioration du logger:
- ajout d'un correlationId géré par AsyncLocalStorage pour que tous les logs d'une même requête puissent être liés
- meilleure gestion des logs de timeout en émettant un log d'erreur. Après de multiples tests, se plug sur req.socket semble être la bonne solution lorsque la connexion est coupée

2024-06-21 07:10 UTC, GaelFerrand commented on back/src/common/middlewares/loggingMiddleware.ts
> +      console.log("close", res.headersSent);
console.log

2024-06-21 07:12 UTC, GaelFerrand approved these changes

2024-06-21 14:55 UTC, silto requested changes
Je pense que c'est chaud d'utiliser async_hooks quand la doc Node dit clairement "Please migrate away from this API, if you can". Au delà des problèmes existants, ça crée de la dette tech si ils suppriment la lib complètement à l'avenir.

2024-06-21 14:55 UTC, silto commented on back/src/common/middlewares/loggingMiddleware.ts
> +import { AsyncResource } from "node:async_hooks";
<img width="1200" alt="Capture d’écran 2024-06-21 à 16 40 39" src="https://github.com/MTES-MCT/trackdechets/assets/2432646/38eadec8-54d6-48c9-a380-c359198d80ec">
A priori l'usage de async_hooks est fortement déconseillée (je vais pas te mentir c'est la première fois que j'entends parler de cette lib donc j'ai pas plus d'infos)

2024-06-21 14:55 UTC, silto commented on libs/back/logger/src/correlationId.ts
> +  const uuid = randomBytes(16).toString("hex");
https://nodejs.org/api/crypto.html#cryptorandomuuidoptions crypto.randomUUID est plus approprié pour ça (moins de risque de collision, et format UUID)

2024-06-21 15:21 UTC, Riron commented on back/src/common/middlewares/loggingMiddleware.ts
> +import { AsyncResource } from "node:async_hooks";
C'est bien `AsyncLocalStorage` qui est utilisé, comme conseillé par ce paragraphe. Simplement ca s'importe depuis `node:async_hooks`

2024-06-24 21:00 UTC, silto commented on back/src/common/middlewares/loggingMiddleware.ts
> +import { AsyncResource } from "node:async_hooks";
ah ok my bad alors

2024-06-24 21:00 UTC, silto approved these changes

2024-06-25 15:21 UTC, merged