Fix/packaging
MTES-MCT/trackdechets pull request #828
Opened 2021-03-29 10:02 UTC by Riron

Bug fix. Essentiellement autour des packagings, et petit fix CSS pour le scroll de la navbar sur mobile.

- [ ] Mettre à jour le change log
---

- [Ticket Trello](https://trello.com/c/NecVIUF7/1286-lors-que-je-veux-modifier-un-bsd-brouillon-je-ne-peux-pas-changer-le-conditionnement-si-avant-le-conditionnement-%C3%A9tait-autre)
- [Ticket](https://trello.com/c/fzYCMUqy/1260-bugs-daffichage-sur-la-modale-consistance-et-autre-conditionnement)
- [Ticket](https://trello.com/c/KvbZecOI/1225-etq-user-je-vois-lancien-conditionnement-sur-le-haut-de-la-modale-apr%C3%A8s-le-reconditionnement-alors-quil-saffiche-bien-sur-le-pdf)
- [Ticket](https://trello.com/c/VS36CdFT/1334-pb-affichage-portable-etq-utilisateur-connect%C3%A9-sur-iphone-je-narrive-pas-%C3%A0-cliquer-sur-mon-compte)

2021-04-01 12:54 UTC, Zhouzi approved these changes

2021-04-01 12:54 UTC, Zhouzi commented on front/src/dashboard/bsdds/view/Components.tsx
> +          <span className="tw-ml-2">[Total {numberOfPackages}]</span>
C'est voulu d'avoir remplacé les parenthèses par des crochets ?

2021-04-01 12:54 UTC, Zhouzi commented on front/src/dashboard/bsdds/view/utils.tsx
> +  return packagingInfo.type[0] + packagingInfo.type.slice(1).toLowerCase();
On exporte une fonction `capitalize` dans `src/common/helper` qui pourrait être sympa ici.

2021-04-01 12:54 UTC, Zhouzi commented on front/src/form/packagings/Packagings.tsx
> +                            setFieldValue(`${name}.${idx}.other`, "")
Je n'ai pas testé mais j'ai l'impression que ça peut créer des comportements surprenants. Du genre si je remplis la description et que je clique sur le select, sans changer la valeur, l'input est remit à zéro. Je test pour vérifier ça 👌

Si ça pose problème, une alternative possible serait d'avoir le select sur `name.index` plutôt que `name.index.type` avec comme valeurs : `[{ type: "OTHER", other: "" }, { type: "BENNE", other: null }]`. Comme ça le changement du type initialise proprement le packaging à part entière.

2021-04-01 13:14 UTC, providenz approved these changes

2021-04-01 13:35 UTC, benoitguigal requested changes
J'ai l'impression que ce bug n'a pas été résolu: https://trello.com/c/NecVIUF7, j'ai toujours un message d'erreur "Le description du conditionnement ne peut être renseignée que lorsque le type de conditionnement est 'AUTRE'." si j'essaye de changer le conditionnement (de "Autres" avec un description à un autre conditionnement, par exemple GRV) après l'enregistrement du brouillon

2021-04-01 13:35 UTC, benoitguigal commented on front/src/dashboard/bsdds/view/Components.tsx
> +          <span className="tw-ml-2">[Total {numberOfPackages}]</span>
Ça donne ça du coup

![Capture d’écran 2021-04-01 à 15 21 39](https://user-images.githubusercontent.com/2269165/113300242-04836300-92fe-11eb-93f3-98a516c8accc.png)

2021-04-01 13:35 UTC, benoitguigal commented on front/src/dashboard/bsdds/view/Components.tsx
> +          <span className="tw-ml-2">[Total {numberOfPackages}]</span>
Je serai d'avis de reprendre le formatage utilisé lors de l'édition du bordereau, à savoir:

> Conditionnement: x colis - 1 GRV, 1Fût, 1 Autre(${description})* 

Il serait bien d'ailleurs à cet endroit que la description ne soit pas en dur, actuellement ça affiche toujours "à préciser"

![Capture d’écran 2021-04-01 à 15 25 28](https://user-images.githubusercontent.com/2269165/113300721-7fe51480-92fe-11eb-9fb1-5808396b245a.png)

2021-04-02 16:18 UTC, Zhouzi commented on front/src/dashboard/bsdds/view/Components.tsx
> +          <span className="tw-ml-2">[Total {numberOfPackages}]</span>
Bien vu, on avait un peu de code dupliqué. J'ai ajouté une fonction qui permet d'afficher le résumé et qui est maintenant utilisé aux deux endroits : a8184597fad875063555e7eb1fed98eb9eb4abdf

Au niveau de l'édition :
<img width="1151" alt="Capture d’écran 2021-04-02 à 18 15 22" src="https://user-images.githubusercontent.com/2291025/113433499-9d3ddf80-93df-11eb-9eac-108163c7a245.png">

Dans l'aperçu détaillé :

<img width="416" alt="Capture d’écran 2021-04-02 à 18 15 31" src="https://user-images.githubusercontent.com/2291025/113433504-9e6f0c80-93df-11eb-8ad0-9eb1f82a1548.png">

2021-04-02 16:43 UTC, Zhouzi commented on front/src/form/packagings/Packagings.tsx
> +                            setFieldValue(`${name}.${idx}.other`, "")
Après avoir testé, il y avait effectivement un comportement étrange où au clique sur le select ça vidait le champ et affichait un message d'erreur comme quoi la description est requise pour un packaging "AUTRE". J'ai corrigé ça en le faisant au `onChange`.

2021-04-02 16:45 UTC, Zhouzi commented
J'ai pu corriger [une partie des problèmes du `select`](https://github.com/MTES-MCT/trackdechets/pull/828#discussion_r606318319) mais ça n'a pas corrigé le problème du message d'erreur qui apparaît quand même. Je n'ai pas eu le temps de creuser, ça a l'air d'être un problème assez tordu parce que le state semble correct mais la validation a l'air de ne pas être synchronisé.

2021-04-06 08:23 UTC, benoitguigal approved these changes

2021-04-06 10:30 UTC, merged