Les codes R12 et D12 autorisés uniquement si le destinataire est TTR [dasris]
MTES-MCT/trackdechets pull request #914
Opened 2021-06-29 09:42 UTC by providenz

Les codes susmentionnés désignent des regroupements et ne sont destinés qu'à des TTRs.

- [ ] Mettre à jour la documentation
- [x] Mettre à jour le change log
 
 
---

- [Ticket Trello](https://trello.com/c/esDZ8vcY/1505-dasris-les-codes-r12-et-d12-autoris%C3%A9s-uniquement-si-le-destinataire-est-ttr)

2021-06-30 08:56 UTC, Zhouzi approved these changes

2021-07-05 07:25 UTC, benoitguigal requested changes

2021-07-05 07:25 UTC, benoitguigal commented on back/src/bsdasris/validation.ts
> +            return isWasteProcessor(recipientCompany);
Il me semble que les TTR correspondent au company type `COLLECTOR` plutôt Cf https://github.com/MTES-MCT/trackdechets/blob/2b9be3c185907daa46ac807552e2decdc2c02097/back/src/companies/typeDefs/company.enums.graphql#L6

2021-07-05 09:05 UTC, providenz commented on back/src/bsdasris/validation.ts
> +            return isWasteProcessor(recipientCompany);
bien vu

2021-07-05 10:03 UTC, benoitguigal approved these changes

2021-07-05 20:15 UTC, merged